{
    firstname: 'Frank',
    surname: 'Lampard',
    dob: '20-06-1978',
    nationality: 'English',
    club: 'Chelsea',
    season: 2006,
    league: 'epl',
    img: '',
    appearances:37,
    goals: 11,
    // gpa:
    },
    {
        firstname: 'Frank',
        surname: 'Lampard',
        dob: '20-06-1978',
        nationality: 'English',
        club: 'Chelsea',
        season: 2007,
        league: 'epl',
        img: '',
        appearances:24,
        goals: 10,
        // gpa:
        },
        {
            firstname: 'Frank',
            surname: 'Lampard',
            dob: '20-06-1978',
            nationality: 'English',
            club: 'Chelsea',
            season: 2008,
            league: 'epl',
            img: '',
            appearances:37,
            goals: 12,
            // gpa:
            },
            {
                firstname: 'Frank',
                surname: 'Lampard',
                dob: '20-06-1978',
                nationality: 'English',
                club: 'Chelsea',
                season: 2009,
                league: 'epl',
                img: '',
                appearances:36,
                goals: 22,
                // gpa:
                },
                {
                    firstname: 'Frank',
                    surname: 'Lampard',
                    dob: '20-06-1978',
                    nationality: 'English',
                    club: 'Chelsea',
                    season: 2010,
                    league: 'epl',
                    img: '',
                    appearances:24,
                    goals: 10,
                    // gpa:
                    },
                    {
                        firstname: 'Frank',
                        surname: 'Lampard',
                        dob: '20-06-1978',
                        nationality: 'English',
                        club: 'Chelsea',
                        season: 2011,
                        league: 'epl',
                        img: '',
                        appearances:30,
                        goals: 11,
                        // gpa:
                        },
                        {
                            firstname: 'Frank',
                            surname: 'Lampard',
                            dob: '20-06-1978',
                            nationality: 'English',
                            club: 'Chelsea',
                            season: 2012,
                            league: 'epl',
                            img: '',
                            appearances:29,
                            goals: 15,
                            // gpa:
                            },