{
    firstname: 'Romelu',
    surname: 'Lukaku',
    dob: '13-05-1993',
    nationality: 'Belgian',
    club: 'Chelsea and Everton (Loan)',
    season: 2013,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.QudVj1iDmey93woF3fhByQHaJ5?w=123&h=180&c=7&r=0&o=5&pid=1.7',
    appearances: 33,
    goals: 15,
    // gpa:
    },
{
    firstname: 'Romelu',
    surname: 'Lukaku',
    dob: '13-05-1993',
    nationality: 'Belgian',
    club: 'Everton',
    season: 2014,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.QudVj1iDmey93woF3fhByQHaJ5?w=123&h=180&c=7&r=0&o=5&pid=1.7',
    appearances: 36,
    goals: 10,
    // gpa:
    },
    {
        firstname: 'Romelu',
        surname: 'Lukaku',
        dob: '13-05-1993',
        nationality: 'Belgian',
        club: 'Everton',
        season: 2015,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.QudVj1iDmey93woF3fhByQHaJ5?w=123&h=180&c=7&r=0&o=5&pid=1.7',
        appearances: 37,
        goals: 18,
        // gpa:
        },
        {
            firstname: 'Romelu',
            surname: 'Lukaku',
            dob: '13-05-1993',
            nationality: 'Belgian',
            club: 'Everton',
            season: 2016,
            league: 'epl',
            img: 'https://th.bing.com/th/id/OIP.QudVj1iDmey93woF3fhByQHaJ5?w=123&h=180&c=7&r=0&o=5&pid=1.7',
            appearances: 37,
            goals: 25,
            // gpa:
            },
            {
                firstname: 'Romelu',
                surname: 'Lukaku',
                dob: '13-05-1993',
                nationality: 'Belgian',
                club: 'Manchester United',
                season: 2017,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.lUFj3FCsUvi07CT5uU1PPAHaLG?w=122&h=183&c=7&r=0&o=5&pid=1.7',
                appearances: 34,
                goals: 16,
                // gpa:
                },
            {
                firstname: 'Romelu',
                surname: 'Lukaku',
                dob: '13-05-1993',
                nationality: 'Belgian',
                club: 'Manchester United',
                season: 2018,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.lUFj3FCsUvi07CT5uU1PPAHaLG?w=122&h=183&c=7&r=0&o=5&pid=1.7',
                appearances: 32,
                goals: 12,
                // gpa:
                },
            {
                firstname: 'Romelu',
                surname: 'Lukaku',
                dob: '13-05-1993',
                nationality: 'Belgian',
                club: 'Chelsea',
                season: 2021,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.1ivKQFawJ8JPoXffvb7JVQHaL0?w=130&h=210&c=7&r=0&o=5&pid=1.7',
                appearances: 26,
                goals: 8,
                // gpa:
                },

                
    