{
    firstname: 'Michael',
    surname: 'Owen',
    dob: '14-12-1979',
    nationality: 'English',
    club: 'Liverpool',
    season: 2001,
    league: 'epl',
    img: '',
    appearances:29 ,
    goals: 19,
    // gpa:
    },
{
    firstname: 'Michael',
    surname: 'Owen',
    dob: '14-12-1979',
    nationality: 'English',
    club: 'Liverpool',
    season: 2002,
    league: 'epl',
    img: '',
    appearances:35 ,
    goals: 19,
    // gpa:
    },
{
    firstname: 'Michael',
    surname: 'Owen',
    dob: '14-12-1979',
    nationality: 'English',
    club: 'Liverpool',
    season: 2003,
    league: 'epl',
    img: '',
    appearances:29 ,
    goals: 16,
    // gpa:
    },