const players = [
    // {
    //     firstname: 'player 1',
    //     surname: 'surname 1',
    //     dob: '19/08/1990',
    //     nationality: 'Testing',
    //     club: 'Test FC',
    //     season: '1993',
    //     league: 'epl',
    //     img: 'www.test.com',
    //     appearances: 50,
    //     goals: 25,
    //     gpa: 0.5   
    // },
    // {
    //     firstname: 'player 2',
    //     surname: 'surname 2',
    //     dob: '19/04/1980',
    //     nationality: 'French',
    //     club: 'Nantes',
    //     season: '1996',
    //     league: 'ligue 1',
    //     img: 'www.test.com',
    //     appearances: 30,
    //     goals: 20,
    //     gpa: 0.66   
    // },
    // {
    //     firstname: 'player 3',
    //     surname: 'surname 3',
    //     dob: '10/02/1978',
    //     nationality: 'English',
    //     club: 'Newcastle United',
    //     season: '1995',
    //     league: 'la liga',
    //     img: 'www.test.com',
    //     appearances: 38,
    //     goals: 38,
    //     gpa: 1   
    // },
    // {
    //     firstname: 'player 4',
    //     surname: 'surname 4',
    //     dob: '19/07/1980',
    //     nationality: 'German',
    //     club: 'Bayern Munich',
    //     season: '1999',
    //     league: 'bundesliga',
    //     img: 'www.test.com',
    //     appearances: 20,
    //     goals: 30,
    //     gpa: 1.5   
    // },
    // {
    //     firstname: 'player 5',
    //     surname: 'Simons',
    //     dob: '19/08/1960',
    //     nationality: 'Spanish',
    //     club: 'Athletico Bilbao',
    //     season: '1992',
    //     league: 'la liga',
    //     img: 'www.test.com',
    //     appearances: 30,
    //     goals: 10,
    //     gpa: 0.3   
    // },

// 1992
// EPL
{
firstname: 'Teddy',
surname: 'Sheringham',
dob: '02-04-1966',
nationality: 'English',
club: 'Nottingham Forest and Tottenham Hotspurs',
season: 1992,
league: 'epl',
img: '',
appearances:38 ,
goals:22 ,
// gpa:
},
{
firstname: 'Les',
surname: 'Ferdinand',
dob: '08-12-1966',
nationality: 'English',
club: 'Queens Park Rangers',
season: 1992,
league: 'epl',
img: '',
appearances:37,
goals: 20,
// gpa:
},
{
firstname: 'Dean',
surname: 'Holdsworth',
dob: '08-11-1968',
nationality: 'English',
club: 'Wimbledon',
season: 1992,
league: 'epl',
img: '',
appearances: 34,
goals: 19,
// gpa:
},
{
firstname: 'Micky',
surname: 'Quinn',
dob: '02-05-1962',
nationality: 'English',
club: 'Coventry City',
season: 1992,
league: 'epl',
img: '',
appearances: 26 ,
goals: 17,
// gpa:
},
{
firstname: 'Alan',
surname: 'Shearer',
dob: '13-08-1970',
nationality: 'English',
club: 'Blackburn Rovers',
season: 1992,
league: 'epl',
img: '',
appearances: 21,
goals: 16,
// gpa:
},
{
firstname: 'David',
surname: 'White',
dob: '30-10-1967',
nationality: 'English',
club: 'Manchester United',
season: 1992,
league: 'epl',
img: '',
appearances:42 ,
goals: 16,
// gpa:
},
{
firstname: 'Brian',
surname: 'Deane',
dob: '07-02-1968',
nationality: 'English',
club: 'Sheffield United',
season: 1992,
league: 'epl',
img: '',
appearances:41 ,
goals: 15,
// gpa:
},
{
firstname: 'Chris',
surname: 'Armstrong',
dob: '19-06-1971',
nationality: 'English',
club: 'Crystal Palace',
season: 1992,
league: 'epl',
img: '',
appearances:35 ,
goals: 15,
// gpa:
},
{
firstname: 'Eric',
surname: 'Cantona',
dob: '24-05-1966',
nationality: 'French',
club: 'Leeds United and Manchester United',
season: 1992,
league: 'epl',
img: '',
appearances: 35 ,
goals: 15,
// gpa:
},
{
firstname: 'Ian',
surname: 'Wright',
dob: '03-11-1963',
nationality: 'English',
club: 'Arsenal',
season: 1992,
league: 'epl',
img: '',
appearances:31 ,
goals: 15,
// gpa:
},
{
firstname: 'Mark',
surname: 'Hughes',
dob: '1-11-1963',
nationality: 'Welsh',
club: 'Manchester United',
season: 1992,
league: 'epl',
img: '',
appearances:41 ,
goals: 15,
// gpa:
},
{
firstname: 'Mark',
surname: 'Robins',
dob: '22-12-1969',
nationality: 'English',
club: 'Norwich City',
season: 1992,
league: 'epl',
img: '',
appearances: 37 ,
goals: 15,
// gpa:
},
{
firstname: 'Matt',
surname: 'Le Tisser',
dob: '14-10-1968',
nationality: 'English',
club: 'Southampton',
season: 1992,
league: 'epl',
img: '',
appearances:40 ,
goals: 15,
// gpa:
},
{
firstname: 'Paul',
surname: 'Wilkinson',
dob: '30-10-1964',
nationality: 'English',
club: 'Middlesbrough',
season: 1992,
league: 'epl',
img: '',
appearances:41 ,
goals: 15,
// gpa:
},

// 1993
// Epl

{
firstname: 'Andy',
surname: 'Cole',
dob: '15-10-1971',
nationality: 'English',
club: 'Newcastle United',
season: 1993,
league: 'epl',
img: '',
appearances:40,
goals: 34,
// gpa:
},
{
firstname: 'Alan',
surname: 'Shearer',
dob: '13-08-1970',
nationality: 'English',
club: 'Blackburn Rovers',
season: 1993,
league: 'epl',
img: '',
appearances: 40,
goals: 31,
// gpa:
},
{
firstname: 'Chris',
surname: 'Sutton',
dob: '10-03-1973',
nationality: 'English',
club: 'Norwich City',
season: 1993,
league: 'epl',
img: '',
appearances: 41,
goals: 25,
// gpa:
},
{
firstname: 'Matt',
surname: 'Le Tisser',
dob: '14-10-1968',
nationality: 'English',
club: 'Southampton',
season: 1993,
league: 'epl',
img: '',
appearances:38 ,
goals: 25,
// gpa:
},
{
firstname: 'Ian',
surname: 'Wright',
dob: '03-11-1963',
nationality: 'English',
club: 'Arsenal',
season: 1993,
league: 'epl',
img: '',
appearances:39 ,
goals: 23,
// gpa:
},
{
firstname: 'Peter',
surname: 'Beardsley',
dob: '10-01-1961',
nationality: 'English',
club: 'Newcastle United',
season: 1993,
league: 'epl',
img: '',
appearances:35 ,
goals: 21,
// gpa:
},
{
firstname: 'Mark',
surname: 'Bright',
dob: '06-06-1962',
nationality: 'English',
club: 'Sheffield Wednesday',
season: 1993,
league: 'epl',
img: '',
appearances:40 ,
goals: 19,
// gpa:
},
{
firstname: 'Eric',
surname: 'Cantona',
dob: '24-05-1966',
nationality: 'French',
club: 'Manchester United',
season: 1993,
league: 'epl',
img: '',
appearances: 34 ,
goals: 18,
// gpa:
},
{
firstname: 'Dean',
surname: 'Holdsworth',
dob: '08-11-1968',
nationality: 'English',
club: 'Wimbledon',
season: 1993,
league: 'epl',
img: '',
appearances: 42,
goals: 17,
// gpa:
},
{
firstname: 'Les',
surname: 'Ferdinand',
dob: '08-12-1966',
nationality: 'English',
club: 'Queens Park Rangers',
season: 1993,
league: 'epl',
img: '',
appearances:36,
goals: 17,
// gpa:
},

// 1994
// Epl
{
firstname: 'Alan',
surname: 'Shearer',
dob: '13-08-1970',
nationality: 'English',
club: 'Blackburn Rovers',
season: 1994,
league: 'epl',
img: '',
appearances: 42,
goals: 34,
// gpa:
},
{
firstname: 'Robbie',
surname: 'Fowler',
dob: '09-02-1975',
nationality: 'English',
club: 'Liverpool',
season: 1994,
league: 'epl',
img: '',
appearances: 42,
goals: 25,
// gpa:
},
{
firstname: 'Les',
surname: 'Ferdinand',
dob: '08-12-1966',
nationality: 'English',
club: 'Queens Park Rangers',
season: 1994,
league: 'epl',
img: '',
appearances:37,
goals: 24,
// gpa:
},
{
firstname: 'Stan',
surname: 'Collymore',
dob: '22-01-1971',
nationality: 'English',
club: 'Nottingham Forest',
season: 1994,
league: 'epl',
img: '',
appearances:37,
goals: 22,
// gpa:
},
{
firstname: 'Andy',
surname: 'Cole',
dob: '15-10-1971',
nationality: 'English',
club: 'Newcastle United and Manchester United',
season: 1994,
league: 'epl',
img: '',
appearances:36,
goals: 21,
// gpa:
},
{
firstname: 'Jurgen',
surname: 'Klinsmann',
dob: '30-07-1964',
nationality: 'German',
club: 'Tottenham Hotspurs',
season: 1994,
league: 'epl',
img: '',
appearances:41,
goals: 20,
// gpa:
},
{
firstname: 'Matt',
surname: 'Le Tisser',
dob: '14-10-1968',
nationality: 'English',
club: 'Southampton',
season: 1994,
league: 'epl',
img: '',
appearances:41 ,
goals: 20,
// gpa:
},
{
firstname: 'Ian',
surname: 'Wright',
dob: '03-11-1963',
nationality: 'English',
club: 'Arsenal',
season: 1994,
league: 'epl',
img: '',
appearances:31 ,
goals: 18,
// gpa:
},
{
firstname: 'Teddy',
surname: 'Sheringham',
dob: '02-04-1966',
nationality: 'English',
club: 'Tottenham Hotspurs',
season: 1994,
league: 'epl',
img: '',
appearances:42 ,
goals:18 ,
// gpa:
},
{
firstname: 'Chris',
surname: 'Sutton',
dob: '10-03-1973',
nationality: 'English',
club: 'Blackburn Rovers',
season: 1994,
league: 'epl',
img: '',
appearances: 40,
goals: 15,
// gpa:
},
{
firstname: 'Dean',
surname: 'Saunders',
dob: '21-06-1964',
nationality: 'Welsh',
club: 'Aston Villa',
season: 1994,
league: 'epl',
img: '',
appearances: 39,
goals: 15,
// gpa:
},
{
firstname: 'Uwe',
surname: 'Rosler',
dob: '15-11-1968',
nationality: 'German',
club: 'Manchester City',
season: 1994,
league: 'epl',
img: '',
appearances: 31,
goals: 15,
// gpa:
},

//1995
//epl

{
    firstname: 'Alan',
    surname: 'Shearer',
    dob: '13-08-1970',
    nationality: 'English',
    club: 'Blackburn Rovers',
    season: 1995,
    league: 'epl',
    img: '',
    appearances: 35,
    goals: 31,
    // gpa:
    },
    {
        firstname: 'Robbie',
        surname: 'Fowler',
        dob: '09-02-1975',
        nationality: 'English',
        club: 'Liverpool',
        season: 1995,
        league: 'epl',
        img: '',
        appearances: 38,
        goals: 28,
        // gpa:
        },
        {
            firstname: 'Les',
            surname: 'Ferdinand',
            dob: '08-12-1966',
            nationality: 'English',
            club: 'Newcastle United',
            season: 1995,
            league: 'epl',
            img: '',
            appearances:37,
            goals: 25,
            // gpa:
            },
            {
                firstname: 'Dwight',
                surname: 'Yorke',
                dob: '03-11-1971',
                nationality: 'Trinidadian and Tobagonian',
                club: 'Aston Villa',
                season: 1995,
                league: 'epl',
                img: '',
                appearances:35,
                goals: 17,
                // gpa:
                },
                {
firstname: 'Teddy',
surname: 'Sheringham',
dob: '02-04-1966',
nationality: 'English',
club: 'Tottenham Hotspurs',
season: 1995,
league: 'epl',
img: '',
appearances:38 ,
goals:16 ,
// gpa:
},
{
firstname: 'Andrei',
surname: 'Kanchelskis',
dob: '02-04-1966',
nationality: 'Ukranian',
club: 'Everton',
season: 1995,
league: 'epl',
img: '',
appearances:32 ,
goals:16 ,
// gpa:
},
{
    firstname: 'Chris',
    surname: 'Armstrong',
    dob: '19-06-1971',
    nationality: 'English',
    club: 'Tottenham Hotspurs',
    season: 1995,
    league: 'epl',
    img: '',
    appearances:36 ,
    goals: 15,
    // gpa:
    },
    {
        firstname: 'Ian',
        surname: 'Wright',
        dob: '03-11-1963',
        nationality: 'English',
        club: 'Arsenal',
        season: 1995,
        league: 'epl',
        img: '',
        appearances:31 ,
        goals: 15,
        // gpa:
        },
        {
            firstname: 'Dion',
            surname: 'Dublin',
            dob: '22-04-1969',
            nationality: 'English',
            club: 'Coventry City',
            season: 1995,
            league: 'epl',
            img: '',
            appearances:34 ,
            goals: 14,
            // gpa:
            },
            {
                firstname: 'Eric',
                surname: 'Cantona',
                dob: '24-05-1966',
                nationality: 'French',
                club: 'Manchester United',
                season: 1995,
                league: 'epl',
                img: '',
                appearances: 30 ,
                goals: 14,
                // gpa:
                },
                {
                    firstname: 'Stan',
                    surname: 'Collymore',
                    dob: '22-01-1971',
                    nationality: 'English',
                    club: 'Liverpool',
                    season: 1995,
                    league: 'epl',
                    img: '',
                    appearances:31,
                    goals: 14,
                    // gpa:
                    },
//1996
//epl
{
    firstname: 'Alan',
    surname: 'Shearer',
    dob: '13-08-1970',
    nationality: 'English',
    club: 'Newcastle United',
    season: 1996,
    league: 'epl',
    img: '',
    appearances: 31,
    goals: 25,
    // gpa:
    },
    {
        firstname: 'Ian',
        surname: 'Wright',
        dob: '03-11-1963',
        nationality: 'English',
        club: 'Arsenal',
        season: 1996,
        league: 'epl',
        img: '',
        appearances:35 ,
        goals: 23,
        // gpa:
        },
    {
        firstname: 'Ole Gunnar',
        surname: 'Solskjær',
        dob: '26-02-1973',
        nationality: 'Norwegian',
        club: 'Manchester United',
        season: 1996,
        league: 'epl',
        img: '',
        appearances:33 ,
        goals: 18,
        // gpa:
        },
        {
            firstname: 'Robbie',
            surname: 'Fowler',
            dob: '09-02-1975',
            nationality: 'English',
            club: 'Liverpool',
            season: 1996,
            league: 'epl',
            img: '',
            appearances: 32,
            goals: 18,
            // gpa:
            },
            {
                firstname: 'Dwight',
                surname: 'Yorke',
                dob: '03-11-1971',
                nationality: 'Trinidadian and Tobagonian',
                club: 'Aston Villa',
                season: 1996,
                league: 'epl',
                img: '',
                appearances:37,
                goals: 17,
                // gpa:
                },
            {
                firstname: 'Fabrizio',
                surname: 'Ravanelli',
                dob: '11-12-1968',
                nationality: 'Italian',
                club: 'Middlesbrough',
                season: 1996,
                league: 'epl',
                img: '',
                appearances:33,
                goals: 16,
                // gpa:
                },
                {
                    firstname: 'Les',
                    surname: 'Ferdinand',
                    dob: '08-12-1966',
                    nationality: 'English',
                    club: 'Newcastle United',
                    season: 1996,
                    league: 'epl',
                    img: '',
                    appearances:31,
                    goals: 16,
                    // gpa:
                    },
                    {
                        firstname: 'Dion',
                        surname: 'Dublin',
                        dob: '22-04-1969',
                        nationality: 'English',
                        club: 'Coventry City',
                        season: 1996,
                        league: 'epl',
                        img: '',
                        appearances:34 ,
                        goals: 13,
                        // gpa:
                        },
                        {
                            firstname: 'Matt',
                            surname: 'Le Tisser',
                            dob: '14-10-1968',
                            nationality: 'English',
                            club: 'Southampton',
                            season: 1996,
                            league: 'epl',
                            img: '',
                            appearances:31 ,
                            goals: 13,
                            // gpa:
                            },
                            {
                                firstname: 'Dennis',
                                surname: 'Bergkamp',
                                dob: '10-05-1969',
                                nationality: 'Dutch',
                                club: 'Arsenal',
                                season: 1996,
                                league: 'epl',
                                img: '',
                                appearances:29 ,
                                goals: 12,
                                // gpa:
                                },
                            {
                                firstname: 'Juninho',
                                surname: 'Paulista',
                                dob: '22-02-1973',
                                nationality: 'Brazilian',
                                club: 'Middlesbrough',
                                season: 1996,
                                league: 'epl',
                                img: '',
                                appearances:35,
                                goals: 12,
                                // gpa:
                                },
                                {
                                    firstname: 'Stan',
                                    surname: 'Collymore',
                                    dob: '22-01-1971',
                                    nationality: 'English',
                                    club: 'Liverpool',
                                    season: 1996,
                                    league: 'epl',
                                    img: '',
                                    appearances:30,
                                    goals: 12,
                                    // gpa:
                                    },
                                    {
                                        firstname: 'Steve',
                                        surname: 'Claridge',
                                        dob: '10-04-1966',
                                        nationality: 'English',
                                        club: 'Leicester City',
                                        season: 1996,
                                        league: 'epl',
                                        img: '',
                                        appearances:32,
                                        goals: 12,
                                        // gpa:
                                        },
        
//1997
//epl

{
    firstname: 'Chris',
    surname: 'Sutton',
    dob: '10-03-1973',
    nationality: 'English',
    club: 'Blackburn Rovers',
    season: 1997,
    league: 'epl',
    img: '',
    appearances: 35,
    goals: 18,
    // gpa:
    },

    {
        firstname: 'Dion',
        surname: 'Dublin',
        dob: '22-04-1969',
        nationality: 'English',
        club: 'Coventry City',
        season: 1997,
        league: 'epl',
        img: '',
        appearances:36 ,
        goals: 18,
        // gpa:
        },

        {
            firstname: 'Michael',
            surname: 'Owen',
            dob: '14-12-1979',
            nationality: 'English',
            club: 'Liverpool',
            season: 1997,
            league: 'epl',
            img: '',
            appearances:36 ,
            goals: 18,
            // gpa:
            },

            {
                firstname: 'Dennis',
                surname: 'Bergkamp',
                dob: '10-05-1969',
                nationality: 'Dutch',
                club: 'Arsenal',
                season: 1997,
                league: 'epl',
                img: '',
                appearances:28 ,
                goals: 16,
                // gpa:
                },
                {
                    firstname: 'Jimmy Floyd',
                    surname: 'Hasselbaink',
                    dob: '27-03-1972',
                    nationality: 'Dutch',
                    club: 'Leeds United',
                    season: 1997,
                    league: 'epl',
                    img: '',
                    appearances:33 ,
                    goals: 16,
                    // gpa:
                    },

                    {
                        firstname: 'Kevin',
                        surname: 'Gallacher',
                        dob: '23-11-1966',
                        nationality: 'Scottish',
                        club: 'Blackburn Rovers',
                        season: 1997,
                        league: 'epl',
                        img: '',
                        appearances:33 ,
                        goals: 16,
                        // gpa:
                        },
                        {
                            firstname: 'John',
                            surname: 'Hartson',
                            dob: '05-04-1975',
                            nationality: 'Welsh',
                            club: 'West Ham United',
                            season: 1997,
                            league: 'epl',
                            img: '',
                            appearances:32,
                            goals: 15,
                            // gpa:
                            },
                            {
                                firstname: 'Darren',
                                surname: 'Huckerby',
                                dob: '23-04-1976',
                                nationality: 'English',
                                club: 'Coventry',
                                season: 1997,
                                league: 'epl',
                                img: '',
                                appearances:34,
                                goals: 14,
                                // gpa:
                                },
                                {
                                    firstname: 'Paolo',
                                    surname: 'Wanchope',
                                    dob: '31-07-1976',
                                    nationality: 'Costa Rican',
                                    club: 'Derby County',
                                    season: 1997,
                                    league: 'epl',
                                    img: '',
                                    appearances:32,
                                    goals: 13,
                                    // gpa:
                                    },

//1998
//epl
{
    firstname: 'Michael',
    surname: 'Owen',
    dob: '14-12-1979',
    nationality: 'English',
    club: 'Liverpool',
    season: 1998,
    league: 'epl',
    img: '',
    appearances:30 ,
    goals: 18,
    // gpa:
    },

{
    firstname: 'Dwight',
    surname: 'Yorke',
    dob: '03-11-1971',
    nationality: 'Trinidadian and Tobagonian',
    club: 'Manchester United',
    season: 1998,
    league: 'epl',
    img: '',
    appearances:32,
    goals: 18,
    // gpa:
    },

    {
        firstname: 'Jimmy Floyd',
        surname: 'Hasselbaink',
        dob: '27-03-1972',
        nationality: 'Dutch',
        club: 'Leeds United',
        season: 1998,
        league: 'epl',
        img: '',
        appearances:36 ,
        goals: 18,
        // gpa:
        },
    
        {
            firstname: 'Andy',
            surname: 'Cole',
            dob: '15-10-1971',
            nationality: 'English',
            club: 'Manchester United',
            season: 1998,
            league: 'epl',
            img: '',
            appearances:32,
            goals: 17,
            // gpa:
            },

            {
                firstname: 'Nicolas',
                surname: 'Anelka',
                dob: '14-03-1979',
                nationality: 'French',
                club: 'Arsenal',
                season: 1998,
                league: 'epl',
                img: '',
                appearances:35,
                goals: 17,
                // gpa:
                },

                {
                    firstname: 'Hamilton',
                    surname: 'Ricard',
                    dob: '12-01-1974',
                    nationality: 'Colombian',
                    club: 'Middlesbrough',
                    season: 1998,
                    league: 'epl',
                    img: '',
                    appearances:36,
                    goals: 15,
                    // gpa:
                    },

    {
    firstname: 'Alan',
    surname: 'Shearer',
    dob: '13-08-1970',
    nationality: 'English',
    club: 'Newcastle United',
    season: 1998,
    league: 'epl',
    img: '',
    appearances: 30,
    goals: 14,
    // gpa:
    },

    {
        firstname: 'Dion',
        surname: 'Dublin',
        dob: '22-04-1969',
        nationality: 'English',
        club: 'Coventry City and Aston Villa',
        season: 1998,
        league: 'epl',
        img: '',
        appearances:34 ,
        goals: 14,
        // gpa:
        },

        {
            firstname: 'Julian',
            surname: 'Joachim',
            dob: '20-09-1974',
            nationality: 'English',
            club: 'Coventry City',
            season: 1998,
            league: 'epl',
            img: '',
            appearances:36 ,
            goals: 14,
            // gpa:
            },

            {
                firstname: 'Robbie',
                surname: 'Fowler',
                dob: '09-02-1975',
                nationality: 'English',
                club: 'Liverpool',
                season: 1998,
                league: 'epl',
                img: '',
                appearances: 25,
                goals: 14,
                // gpa:
                },

//1999
//epl

{
    firstname: 'Kevin',
    surname: 'Phillips',
    dob: '25-07-1973',
    nationality: 'English',
    club: 'Sunderland',
    season: 1999,
    league: 'epl',
    img: '',
    appearances: 36,
    goals: 30,
    // gpa:
    },
    {
        firstname: 'Alan',
        surname: 'Shearer',
        dob: '13-08-1970',
        nationality: 'English',
        club: 'Newcastle United',
        season: 1999,
        league: 'epl',
        img: '',
        appearances: 37,
        goals: 23,
        // gpa:
        },

        {
            firstname: 'Dwight',
            surname: 'Yorke',
            dob: '03-11-1971',
            nationality: 'Trinidadian and Tobagonian',
            club: 'Manchester United',
            season: 1999,
            league: 'epl',
            img: '',
            appearances:32,
            goals: 20,
            // gpa:
            },

            {
                firstname: 'Andy',
                surname: 'Cole',
                dob: '15-10-1971',
                nationality: 'English',
                club: 'Manchester United',
                season: 1999,
                league: 'epl',
                img: '',
                appearances:28,
                goals: 19,
                // gpa:
                },
                {
                    firstname: 'Micael',
                    surname: 'Bridges',
                    dob: '05-08-1978',
                    nationality: 'English',
                    club: 'Leeds United',
                    season: 1999,
                    league: 'epl',
                    img: '',
                    appearances:34,
                    goals: 19,
                    // gpa:
                    },
                    {
                        firstname: 'Thierry',
                        surname: 'Henry',
                        dob: '17-08-1977',
                        nationality: 'French',
                        club: 'Arsenal',
                        season: 1999,
                        league: 'epl',
                        img: '',
                        appearances:31,
                        goals: 17,
                        // gpa:
                        },
                        {
                            firstname: 'Paolo',
                            surname: 'Di Canio',
                            dob: '09-07-1968',
                            nationality: 'Italian',
                            club: 'West Ham United',
                            season: 1999,
                            league: 'epl',
                            img: '',
                            appearances:30,
                            goals: 16,
                            // gpa:
                            },
                            {
                                firstname: 'Chris',
                                surname: 'Armstrong',
                                dob: '19-06-1971',
                                nationality: 'English',
                                club: 'Tottenham Hotspurs',
                                season: 1999,
                                league: 'epl',
                                img: '',
                                appearances:31 ,
                                goals: 14,
                                // gpa:
                                },
                                {
                                    firstname: 'Niall',
                                    surname: 'Quinn',
                                    dob: '06-10-1966',
                                    nationality: 'Irish',
                                    club: 'Sunderlnd',
                                    season: 1999,
                                    league: 'epl',
                                    img: '',
                                    appearances:37 ,
                                    goals: 14,
                                    // gpa:
                                    },
                                    {
                                        firstname: 'Stefan',
                                        surname: 'Iversen',
                                        dob: '10-11-1976',
                                        nationality: 'Norwegian',
                                        club: 'Tottenham Hotspurs',
                                        season: 1999,
                                        league: 'epl',
                                        img: '',
                                        appearances:36 ,
                                        goals: 14,
                                        // gpa:
                                        },

]

export default players;