const players = [
    // {
    //     firstname: 'player 1',
    //     surname: 'surname 1',
    //     dob: '19/08/1990',
    //     nationality: 'Testing',
    //     club: 'Test FC',
    //     season: '1993',
    //     league: 'epl',
    //     img: 'www.test.com',
    //     appearances: 50,
    //     goals: 25,
    //     gpa: 0.5   
    // },
    // {
    //     firstname: 'player 2',
    //     surname: 'surname 2',
    //     dob: '19/04/1980',
    //     nationality: 'French',
    //     club: 'Nantes',
    //     season: '1996',
    //     league: 'ligue 1',
    //     img: 'www.test.com',
    //     appearances: 30,
    //     goals: 20,
    //     gpa: 0.66   
    // },
    // {
    //     firstname: 'player 3',
    //     surname: 'surname 3',
    //     dob: '10/02/1978',
    //     nationality: 'English',
    //     club: 'Newcastle United',
    //     season: '1995',
    //     league: 'la liga',
    //     img: 'www.test.com',
    //     appearances: 38,
    //     goals: 38,
    //     gpa: 1   
    // },
    // {
    //     firstname: 'player 4',
    //     surname: 'surname 4',
    //     dob: '19/07/1980',
    //     nationality: 'German',
    //     club: 'Bayern Munich',
    //     season: '1999',
    //     league: 'bundesliga',
    //     img: 'www.test.com',
    //     appearances: 20,
    //     goals: 30,
    //     gpa: 1.5   
    // },
    // {
    //     firstname: 'player 5',
    //     surname: 'Simons',
    //     dob: '19/08/1960',
    //     nationality: 'Spanish',
    //     club: 'Athletico Bilbao',
    //     season: '1992',
    //     league: 'la liga',
    //     img: 'www.test.com',
    //     appearances: 30,
    //     goals: 10,
    //     gpa: 0.3   
    // },

// 1992
// EPL
{
firstname: 'Teddy',
surname: 'Sheringham',
dob: '02-04-1966',
nationality: 'English',
club: 'Nottingham Forest and Tottenham Hotspur',
season: 1992,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.AepfDkAzDXrBnXyeVFofcQHaLI?w=123&h=185&c=7&r=0&o=5&pid=1.7',
appearances:38 ,
goals:22 ,
// gpa:
},
{
firstname: 'Les',
surname: 'Ferdinand',
dob: '08-12-1966',
nationality: 'English',
club: 'Queens Park Rangers',
season: 1992,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.1VrgRDWPjeyZ596uH_KK5QAAAA?w=135&h=180&c=7&r=0&o=5&pid=1.7',
appearances:37,
goals: 20,
// gpa:
},
{
firstname: 'Dean',
surname: 'Holdsworth',
dob: '08-11-1968',
nationality: 'English',
club: 'Wimbledon',
season: 1992,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.-GJ_mHsI1SirVOa-tmAQIAHaJ0?w=125&h=180&c=7&r=0&o=5&pid=1.7',
appearances: 34,
goals: 19,
// gpa:
},
{
firstname: 'Micky',
surname: 'Quinn',
dob: '02-05-1962',
nationality: 'English',
club: 'Coventry City',
season: 1992,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.vK4WChJR3x2dNMPqm5rB7wHaLH?w=125&h=187&c=7&r=0&o=5&pid=1.7',
appearances: 26 ,
goals: 17,
// gpa:
},
{
firstname: 'Alan',
surname: 'Shearer',
dob: '13-08-1970',
nationality: 'English',
club: 'Blackburn Rovers',
season: 1992,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.erawO-6jnbYRRWY6aLX97gHaKv?w=112&h=180&c=7&r=0&o=5&pid=1.7',
appearances: 21,
goals: 16,
// gpa:
},
{
firstname: 'David',
surname: 'White',
dob: '30-10-1967',
nationality: 'English',
club: 'Manchester City',
season: 1992,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.4W4INOLzlqpwuiXxPUyjiAHaLI?w=115&h=180&c=7&r=0&o=5&pid=1.7',
appearances:42 ,
goals: 16,
// gpa:
},
{
firstname: 'Brian',
surname: 'Deane',
dob: '07-02-1968',
nationality: 'English',
club: 'Sheffield United',
season: 1992,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.nzCcgoX810rtXhpY-1nUrgHaFj?w=185&h=139&c=7&r=0&o=5&pid=1.7',
appearances:41 ,
goals: 15,
// gpa:
},
{
firstname: 'Chris',
surname: 'Armstrong',
dob: '19-06-1971',
nationality: 'English',
club: 'Crystal Palace',
season: 1992,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.OCpi2vdsGSkvp6jvCsLLogHaKv?w=114&h=180&c=7&r=0&o=5&pid=1.7',
appearances:35 ,
goals: 15,
// gpa:
},
{
firstname: 'Eric',
surname: 'Cantona',
dob: '24-05-1966',
nationality: 'French',
club: 'Leeds United and Manchester United',
season: 1992,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.JASNhrG8a405MBW0TzTtWAHaLC?w=134&h=201&c=7&r=0&o=5&pid=1.7',
appearances: 35 ,
goals: 15,
// gpa:
},
{
firstname: 'Ian',
surname: 'Wright',
dob: '03-11-1963',
nationality: 'English',
club: 'Arsenal',
season: 1992,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.Isyb8ihuxCa4DXSm5OblOAAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
appearances:31 ,
goals: 15,
// gpa:
},
{
firstname: 'Mark',
surname: 'Hughes',
dob: '1-11-1963',
nationality: 'Welsh',
club: 'Manchester United',
season: 1992,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.q2b6YqG2nKAY3pzcneCD-QAAAA?w=185&h=278&c=7&r=0&o=5&pid=1.7',
appearances:41 ,
goals: 15,
// gpa:
},
{
firstname: 'Mark',
surname: 'Robins',
dob: '22-12-1969',
nationality: 'English',
club: 'Norwich City',
season: 1992,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.EabFbWClayq9J4hOvGqtZAHaLR?w=115&h=180&c=7&r=0&o=5&pid=1.7',
appearances: 37 ,
goals: 15,
// gpa:
},
{
firstname: 'Matt',
surname: 'Le Tisser',
dob: '14-10-1968',
nationality: 'English',
club: 'Southampton',
season: 1992,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.NpIVRa55-s5RA17HZPQ_fwHaK2?w=125&h=184&c=7&r=0&o=5&pid=1.7',
appearances:40 ,
goals: 15,
// gpa:
},
{
firstname: 'Paul',
surname: 'Wilkinson',
dob: '30-10-1964',
nationality: 'English',
club: 'Middlesbrough',
season: 1992,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.sZrvfkNNJKgA7ZId3OW-SwHaKP?w=121&h=180&c=7&r=0&o=5&pid=1.7',
appearances:41 ,
goals: 15,
// gpa:
},

// 1993
// Epl

{
firstname: 'Andy',
surname: 'Cole',
dob: '15-10-1971',
nationality: 'English',
club: 'Newcastle United',
season: 1993,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.eJyu6vDYOUN4dNdjahnI3AHaJt?w=135&h=180&c=7&r=0&o=5&pid=1.7',
appearances:40,
goals: 34,
// gpa:
},
{
firstname: 'Alan',
surname: 'Shearer',
dob: '13-08-1970',
nationality: 'English',
club: 'Blackburn Rovers',
season: 1993,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.erawO-6jnbYRRWY6aLX97gHaKv?w=112&h=180&c=7&r=0&o=5&pid=1.7',
appearances: 40,
goals: 31,
// gpa:
},
{
firstname: 'Chris',
surname: 'Sutton',
dob: '10-03-1973',
nationality: 'English',
club: 'Norwich City',
season: 1993,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.Im5VKIVvvQr7TBH8u-gA7gHaKp?w=116&h=180&c=7&r=0&o=5&pid=1.7',
appearances: 41,
goals: 25,
// gpa:
},
{
firstname: 'Matt',
surname: 'Le Tisser',
dob: '14-10-1968',
nationality: 'English',
club: 'Southampton',
season: 1993,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.NpIVRa55-s5RA17HZPQ_fwHaK2?w=125&h=184&c=7&r=0&o=5&pid=1.7',
appearances:38 ,
goals: 25,
// gpa:
},
{
firstname: 'Ian',
surname: 'Wright',
dob: '03-11-1963',
nationality: 'English',
club: 'Arsenal',
season: 1993,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.Isyb8ihuxCa4DXSm5OblOAAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
appearances:39 ,
goals: 23,
// gpa:
},
{
firstname: 'Peter',
surname: 'Beardsley',
dob: '10-01-1961',
nationality: 'English',
club: 'Newcastle United',
season: 1993,
league: 'epl',
img: 'https://th.bing.com/th?q=Peter+Beardsley+Newcastle&w=120&h=120&c=1&rs=1&qlt=90&cb=1&pid=InlineBlock&mkt=en-GB&cc=GB&setlang=en&adlt=moderate&t=1&mw=247',
appearances:35 ,
goals: 21,
// gpa:
},
{
firstname: 'Mark',
surname: 'Bright',
dob: '06-06-1962',
nationality: 'English',
club: 'Sheffield Wednesday',
season: 1993,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.RO8ufX3EqTkC__SR2PelDQAAAA?w=185&h=231&c=7&r=0&o=5&pid=1.7',
appearances:40 ,
goals: 19,
// gpa:
},
{
firstname: 'Eric',
surname: 'Cantona',
dob: '24-05-1966',
nationality: 'French',
club: 'Manchester United',
season: 1993,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.JASNhrG8a405MBW0TzTtWAHaLC?w=134&h=201&c=7&r=0&o=5&pid=1.7',
appearances: 34 ,
goals: 18,
// gpa:
},
{
firstname: 'Dean',
surname: 'Holdsworth',
dob: '08-11-1968',
nationality: 'English',
club: 'Wimbledon',
season: 1993,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.-GJ_mHsI1SirVOa-tmAQIAHaJ0?w=125&h=180&c=7&r=0&o=5&pid=1.7',
appearances: 42,
goals: 17,
// gpa:
},
{
firstname: 'Les',
surname: 'Ferdinand',
dob: '08-12-1966',
nationality: 'English',
club: 'Queens Park Rangers',
season: 1993,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.1VrgRDWPjeyZ596uH_KK5QAAAA?w=135&h=180&c=7&r=0&o=5&pid=1.7',
appearances:36,
goals: 17,
// gpa:
},

// 1994
// Epl
{
firstname: 'Alan',
surname: 'Shearer',
dob: '13-08-1970',
nationality: 'English',
club: 'Blackburn Rovers',
season: 1994,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.erawO-6jnbYRRWY6aLX97gHaKv?w=112&h=180&c=7&r=0&o=5&pid=1.7',
appearances: 42,
goals: 34,
// gpa:
},
{
firstname: 'Robbie',
surname: 'Fowler',
dob: '09-02-1975',
nationality: 'English',
club: 'Liverpool',
season: 1994,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.QXTNLL4fhlRaSvx4CIXN2AHaHj?w=183&h=187&c=7&r=0&o=5&pid=1.7',
appearances: 42,
goals: 25,
// gpa:
},
{
firstname: 'Les',
surname: 'Ferdinand',
dob: '08-12-1966',
nationality: 'English',
club: 'Queens Park Rangers',
season: 1994,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.1VrgRDWPjeyZ596uH_KK5QAAAA?w=135&h=180&c=7&r=0&o=5&pid=1.7',
appearances:37,
goals: 24,
// gpa:
},
{
firstname: 'Stan',
surname: 'Collymore',
dob: '22-01-1971',
nationality: 'English',
club: 'Nottingham Forest',
season: 1994,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.xnUjzeC-OUgkCpjk2NAzUwAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
appearances:37,
goals: 22,
// gpa:
},
{
firstname: 'Andy',
surname: 'Cole',
dob: '15-10-1971',
nationality: 'English',
club: 'Newcastle United and Manchester United',
season: 1994,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.d0LgH4PuRQ_azNAGCN6fxAAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
appearances:36,
goals: 21,
// gpa:
},
{
firstname: 'Jurgen',
surname: 'Klinsmann',
dob: '30-07-1964',
nationality: 'German',
club: 'Tottenham Hotspur',
season: 1994,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.B3RgOMqu7M4QfkvGYaQg7AHaJw?w=147&h=194&c=7&r=0&o=5&pid=1.7',
appearances:41,
goals: 20,
// gpa:
},
{
firstname: 'Matt',
surname: 'Le Tisser',
dob: '14-10-1968',
nationality: 'English',
club: 'Southampton',
season: 1994,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.NpIVRa55-s5RA17HZPQ_fwHaK2?w=125&h=184&c=7&r=0&o=5&pid=1.7',
appearances:41 ,
goals: 20,
// gpa:
},
{
firstname: 'Ian',
surname: 'Wright',
dob: '03-11-1963',
nationality: 'English',
club: 'Arsenal',
season: 1994,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.Isyb8ihuxCa4DXSm5OblOAAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
appearances:31 ,
goals: 18,
// gpa:
},
{
firstname: 'Teddy',
surname: 'Sheringham',
dob: '02-04-1966',
nationality: 'English',
club: 'Tottenham Hotspur',
season: 1994,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.AepfDkAzDXrBnXyeVFofcQHaLI?w=123&h=185&c=7&r=0&o=5&pid=1.7',
appearances:42 ,
goals:18 ,
// gpa:
},
{
firstname: 'Chris',
surname: 'Sutton',
dob: '10-03-1973',
nationality: 'English',
club: 'Blackburn Rovers',
season: 1994,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.pynJtosQhYzFh_U05zVaCQHaJY?w=185&h=234&c=7&r=0&o=5&pid=1.7',
appearances: 40,
goals: 15,
// gpa:
},
{
firstname: 'Dean',
surname: 'Saunders',
dob: '21-06-1964',
nationality: 'Welsh',
club: 'Aston Villa',
season: 1994,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.C-0cq1WKKb3lG7oGB1tFDwHaK3?w=185&h=271&c=7&r=0&o=5&pid=1.7',
appearances: 39,
goals: 15,
// gpa:
},
{
firstname: 'Uwe',
surname: 'Rosler',
dob: '15-11-1968',
nationality: 'German',
club: 'Manchester City',
season: 1994,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.5eh15sFCs5Coa9xzlmGnaQHaKJ?w=119&h=180&c=7&r=0&o=5&pid=1.7',
appearances: 31,
goals: 15,
// gpa:
},

//1995
//epl

{
    firstname: 'Alan',
    surname: 'Shearer',
    dob: '13-08-1970',
    nationality: 'English',
    club: 'Blackburn Rovers',
    season: 1995,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.erawO-6jnbYRRWY6aLX97gHaKv?w=112&h=180&c=7&r=0&o=5&pid=1.7',
    appearances: 35,
    goals: 31,
    // gpa:
    },
    {
        firstname: 'Robbie',
        surname: 'Fowler',
        dob: '09-02-1975',
        nationality: 'English',
        club: 'Liverpool',
        season: 1995,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.QXTNLL4fhlRaSvx4CIXN2AHaHj?w=183&h=187&c=7&r=0&o=5&pid=1.7',
        appearances: 38,
        goals: 28,
        // gpa:
        },
        {
            firstname: 'Les',
            surname: 'Ferdinand',
            dob: '08-12-1966',
            nationality: 'English',
            club: 'Newcastle United',
            season: 1995,
            league: 'epl',
            img: 'https://th.bing.com/th/id/OIP.C0e5dAb01xnpfal6qAf20AHaKu?w=115&h=180&c=7&r=0&o=5&pid=1.7',
            appearances:37,
            goals: 25,
            // gpa:
            },
            {
                firstname: 'Dwight',
                surname: 'Yorke',
                dob: '03-11-1971',
                nationality: 'Trinidadian and Tobagonian',
                club: 'Aston Villa',
                season: 1995,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.8-DRuEkBFcazEz3d1Z75hwHaHa?w=185&h=185&c=7&r=0&o=5&pid=1.7',
                appearances:35,
                goals: 17,
                // gpa:
                },
                {
firstname: 'Teddy',
surname: 'Sheringham',
dob: '02-04-1966',
nationality: 'English',
club: 'Tottenham Hotspur',
season: 1995,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.AepfDkAzDXrBnXyeVFofcQHaLI?w=123&h=185&c=7&r=0&o=5&pid=1.7',
appearances:38 ,
goals:16 ,
// gpa:
},
{
firstname: 'Andrei',
surname: 'Kanchelskis',
dob: '02-04-1966',
nationality: 'Ukranian',
club: 'Everton',
season: 1995,
league: 'epl',
img: 'https://th.bing.com/th/id/OIP.aIR1PzVi1Wttxm7xCtnYfwHaLQ?w=115&h=180&c=7&r=0&o=5&pid=1.7',
appearances:32 ,
goals:16 ,
// gpa:
},
{
    firstname: 'Chris',
    surname: 'Armstrong',
    dob: '19-06-1971',
    nationality: 'English',
    club: 'Tottenham Hotspur',
    season: 1995,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.QwhLkgUxds6lSJu7IEYJpwHaJj?w=185&h=238&c=7&r=0&o=5&pid=1.7',
    appearances:36 ,
    goals: 15,
    // gpa:
    },
    {
        firstname: 'Ian',
        surname: 'Wright',
        dob: '03-11-1963',
        nationality: 'English',
        club: 'Arsenal',
        season: 1995,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.Isyb8ihuxCa4DXSm5OblOAAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
        appearances:31 ,
        goals: 15,
        // gpa:
        },
        {
            firstname: 'Dion',
            surname: 'Dublin',
            dob: '22-04-1969',
            nationality: 'English',
            club: 'Coventry City',
            season: 1995,
            league: 'epl',
            img: 'https://th.bing.com/th/id/OIP.yBq48LJL4341KGPumZ7VIQHaIP?w=185&h=205&c=7&r=0&o=5&pid=1.7',
            appearances:34 ,
            goals: 14,
            // gpa:
            },
            {
                firstname: 'Eric',
                surname: 'Cantona',
                dob: '24-05-1966',
                nationality: 'French',
                club: 'Manchester United',
                season: 1995,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.JASNhrG8a405MBW0TzTtWAHaLC?w=134&h=201&c=7&r=0&o=5&pid=1.7',
                appearances: 30 ,
                goals: 14,
                // gpa:
                },
                {
                    firstname: 'Stan',
                    surname: 'Collymore',
                    dob: '22-01-1971',
                    nationality: 'English',
                    club: 'Liverpool',
                    season: 1995,
                    league: 'epl',
                    img: 'https://th.bing.com/th/id/OIP.PU1u-kwiALStp4KSWjCK1QHaKR?w=144&h=200&c=7&r=0&o=5&pid=1.7',
                    appearances:31,
                    goals: 14,
                    // gpa:
                    },
//1996
//epl
{
    firstname: 'Alan',
    surname: 'Shearer',
    dob: '13-08-1970',
    nationality: 'English',
    club: 'Newcastle United',
    season: 1996,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.V4Q11O7QTJ_vVOv57O-7PwHaJU?w=135&h=180&c=7&r=0&o=5&pid=1.7',
    appearances: 31,
    goals: 25,
    // gpa:
    },
    {
        firstname: 'Ian',
        surname: 'Wright',
        dob: '03-11-1963',
        nationality: 'English',
        club: 'Arsenal',
        season: 1996,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.Isyb8ihuxCa4DXSm5OblOAAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
        appearances:35 ,
        goals: 23,
        // gpa:
        },
    {
        firstname: 'Ole Gunnar',
        surname: 'Solskjær',
        dob: '26-02-1973',
        nationality: 'Norwegian',
        club: 'Manchester United',
        season: 1996,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.x0hwff2JjKEWqcb3fKOpdgHaHa?w=160&h=180&c=7&r=0&o=5&pid=1.7',
        appearances:33 ,
        goals: 18,
        // gpa:
        },
        {
            firstname: 'Robbie',
            surname: 'Fowler',
            dob: '09-02-1975',
            nationality: 'English',
            club: 'Liverpool',
            season: 1996,
            league: 'epl',
            img: 'https://th.bing.com/th/id/OIP.QXTNLL4fhlRaSvx4CIXN2AHaHj?w=183&h=187&c=7&r=0&o=5&pid=1.7',
            appearances: 32,
            goals: 18,
            // gpa:
            },
            {
                firstname: 'Dwight',
                surname: 'Yorke',
                dob: '03-11-1971',
                nationality: 'Trinidadian and Tobagonian',
                club: 'Aston Villa',
                season: 1996,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.8-DRuEkBFcazEz3d1Z75hwHaHa?w=185&h=185&c=7&r=0&o=5&pid=1.7',
                appearances:37,
                goals: 17,
                // gpa:
                },
            {
                firstname: 'Fabrizio',
                surname: 'Ravanelli',
                dob: '11-12-1968',
                nationality: 'Italian',
                club: 'Middlesbrough',
                season: 1996,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.Rz0s0afsgnOiZ63ujvuodAHaKP?w=126&h=180&c=7&r=0&o=5&pid=1.7',
                appearances:33,
                goals: 16,
                // gpa:
                },
                {
                    firstname: 'Les',
                    surname: 'Ferdinand',
                    dob: '08-12-1966',
                    nationality: 'English',
                    club: 'Newcastle United',
                    season: 1996,
                    league: 'epl',
                    img: 'https://th.bing.com/th/id/OIP.C0e5dAb01xnpfal6qAf20AHaKu?w=115&h=180&c=7&r=0&o=5&pid=1.7',
                    appearances:31,
                    goals: 16,
                    // gpa:
                    },
                    {
                        firstname: 'Dion',
                        surname: 'Dublin',
                        dob: '22-04-1969',
                        nationality: 'English',
                        club: 'Coventry City',
                        season: 1996,
                        league: 'epl',
                        img: 'https://th.bing.com/th/id/OIP.yBq48LJL4341KGPumZ7VIQHaIP?w=185&h=205&c=7&r=0&o=5&pid=1.7',
                        appearances:34 ,
                        goals: 13,
                        // gpa:
                        },
                        {
                            firstname: 'Matt',
                            surname: 'Le Tisser',
                            dob: '14-10-1968',
                            nationality: 'English',
                            club: 'Southampton',
                            season: 1996,
                            league: 'epl',
                            img: 'https://th.bing.com/th/id/OIP.NpIVRa55-s5RA17HZPQ_fwHaK2?w=125&h=184&c=7&r=0&o=5&pid=1.7',
                            appearances:31 ,
                            goals: 13,
                            // gpa:
                            },
                            {
                                firstname: 'Dennis',
                                surname: 'Bergkamp',
                                dob: '10-05-1969',
                                nationality: 'Dutch',
                                club: 'Arsenal',
                                season: 1996,
                                league: 'epl',
                                img: 'https://th.bing.com/th/id/OIP.N1eeiBHwbvHqu1BSYlV9KAAAAA?w=185&h=251&c=7&r=0&o=5&pid=1.7',
                                appearances:29 ,
                                goals: 12,
                                // gpa:
                                },
                            {
                                firstname: 'Juninho',
                                surname: 'Paulista',
                                dob: '22-02-1973',
                                nationality: 'Brazilian',
                                club: 'Middlesbrough',
                                season: 1996,
                                league: 'epl',
                                img: 'https://th.bing.com/th/id/OIP.8gJljKNKS4fxhqLxBYBlzgHaL2?w=116&h=187&c=7&r=0&o=5&pid=1.7',
                                appearances:35,
                                goals: 12,
                                // gpa:
                                },
                                {
                                    firstname: 'Stan',
                                    surname: 'Collymore',
                                    dob: '22-01-1971',
                                    nationality: 'English',
                                    club: 'Liverpool',
                                    season: 1996,
                                    league: 'epl',
                                    img: 'https://th.bing.com/th/id/OIP.PU1u-kwiALStp4KSWjCK1QHaKR?w=144&h=200&c=7&r=0&o=5&pid=1.7',
                                    appearances:30,
                                    goals: 12,
                                    // gpa:
                                    },
                                    {
                                        firstname: 'Steve',
                                        surname: 'Claridge',
                                        dob: '10-04-1966',
                                        nationality: 'English',
                                        club: 'Leicester City',
                                        season: 1996,
                                        league: 'epl',
                                        img: 'https://th.bing.com/th/id/OIP.pe6yp8NofeE8AW6RM8fw4gHaJV?w=142&h=180&c=7&r=0&o=5&pid=1.7',
                                        appearances:32,
                                        goals: 12,
                                        // gpa:
                                        },
        
//1997
//epl

{
    firstname: 'Chris',
    surname: 'Sutton',
    dob: '10-03-1973',
    nationality: 'English',
    club: 'Blackburn Rovers',
    season: 1997,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.pynJtosQhYzFh_U05zVaCQHaJY?w=185&h=234&c=7&r=0&o=5&pid=1.7',
    appearances: 35,
    goals: 18,
    // gpa:
    },

    {
        firstname: 'Dion',
        surname: 'Dublin',
        dob: '22-04-1969',
        nationality: 'English',
        club: 'Coventry City',
        season: 1997,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.yBq48LJL4341KGPumZ7VIQHaIP?w=185&h=205&c=7&r=0&o=5&pid=1.7',
        appearances:36 ,
        goals: 18,
        // gpa:
        },

        {
            firstname: 'Michael',
            surname: 'Owen',
            dob: '14-12-1979',
            nationality: 'English',
            club: 'Liverpool',
            season: 1997,
            league: 'epl',
            img: 'https://th.bing.com/th?id=OIF.9PgDPpRq%2f0RsIai2FtImiQ&w=184&h=180&c=7&r=0&o=5&pid=1.7',
            appearances:36 ,
            goals: 18,
            // gpa:
            },

            {
                firstname: 'Dennis',
                surname: 'Bergkamp',
                dob: '10-05-1969',
                nationality: 'Dutch',
                club: 'Arsenal',
                season: 1997,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.N1eeiBHwbvHqu1BSYlV9KAAAAA?w=185&h=251&c=7&r=0&o=5&pid=1.7',
                appearances:28 ,
                goals: 16,
                // gpa:
                },
                {
                    firstname: 'Jimmy Floyd',
                    surname: 'Hasselbaink',
                    dob: '27-03-1972',
                    nationality: 'Dutch',
                    club: 'Leeds United',
                    season: 1997,
                    league: 'epl',
                    img: 'https://th.bing.com/th/id/OIP.MBD8KSLPJfMxEN-H_zGwGQHaE7?w=226&h=180&c=7&r=0&o=5&pid=1.7',
                    appearances:33 ,
                    goals: 16,
                    // gpa:
                    },

                    {
                        firstname: 'Kevin',
                        surname: 'Gallacher',
                        dob: '23-11-1966',
                        nationality: 'Scottish',
                        club: 'Blackburn Rovers',
                        season: 1997,
                        league: 'epl',
                        img: 'https://th.bing.com/th/id/OIP.uRg96-aQfoInaAmC46vFmQAAAA?w=117&h=180&c=7&r=0&o=5&pid=1.7',
                        appearances:33 ,
                        goals: 16,
                        // gpa:
                        },
                        {
                            firstname: 'John',
                            surname: 'Hartson',
                            dob: '05-04-1975',
                            nationality: 'Welsh',
                            club: 'West Ham United',
                            season: 1997,
                            league: 'epl',
                            img: 'https://th.bing.com/th/id/OIP.awV4gojhBzRhOXuTpDfvAAHaJZ?w=185&h=234&c=7&r=0&o=5&pid=1.7',
                            appearances:32,
                            goals: 15,
                            // gpa:
                            },
                            {
                                firstname: 'Darren',
                                surname: 'Huckerby',
                                dob: '23-04-1976',
                                nationality: 'English',
                                club: 'Coventry',
                                season: 1997,
                                league: 'epl',
                                img: 'https://th.bing.com/th/id/OIP.3NRIaEd7IvkiZQOglslL_gHaLJ?w=185&h=279&c=7&r=0&o=5&pid=1.7',
                                appearances:34,
                                goals: 14,
                                // gpa:
                                },
                                {
                                    firstname: 'Paolo',
                                    surname: 'Wanchope',
                                    dob: '31-07-1976',
                                    nationality: 'Costa Rican',
                                    club: 'Derby County',
                                    season: 1997,
                                    league: 'epl',
                                    img: 'https://th.bing.com/th/id/OIP.ND6Cn_R2YgaITysY6Jd3-wHaHa?w=168&h=180&c=7&r=0&o=5&pid=1.7',
                                    appearances:32,
                                    goals: 13,
                                    // gpa:
                                    },

//1998
//epl
{
    firstname: 'Michael',
    surname: 'Owen',
    dob: '14-12-1979',
    nationality: 'English',
    club: 'Liverpool',
    season: 1998,
    league: 'epl',
    img: 'https://th.bing.com/th?id=OIF.9PgDPpRq%2f0RsIai2FtImiQ&w=184&h=180&c=7&r=0&o=5&pid=1.7',
    appearances:30 ,
    goals: 18,
    // gpa:
    },

{
    firstname: 'Dwight',
    surname: 'Yorke',
    dob: '03-11-1971',
    nationality: 'Trinidadian and Tobagonian',
    club: 'Aston Villa and Manchester United',
    season: 1998,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.IVGBeBTr13zdU5qee83QlgHaK3?w=125&h=185&c=7&r=0&o=5&pid=1.7',
    appearances:33,
    goals: 18,
    // gpa:
    },

    {
        firstname: 'Jimmy Floyd',
        surname: 'Hasselbaink',
        dob: '27-03-1972',
        nationality: 'Dutch',
        club: 'Leeds United',
        season: 1998,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.MBD8KSLPJfMxEN-H_zGwGQHaE7?w=226&h=180&c=7&r=0&o=5&pid=1.7',
        appearances:36 ,
        goals: 18,
        // gpa:
        },
    
        {
            firstname: 'Andy',
            surname: 'Cole',
            dob: '15-10-1971',
            nationality: 'English',
            club: 'Manchester United',
            season: 1998,
            league: 'epl',
            img: 'https://th.bing.com/th/id/OIP.d0LgH4PuRQ_azNAGCN6fxAAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
            appearances:32,
            goals: 17,
            // gpa:
            },

            {
                firstname: 'Nicolas',
                surname: 'Anelka',
                dob: '14-03-1979',
                nationality: 'French',
                club: 'Arsenal',
                season: 1998,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.s__EU8xnRwG8om_OkXVwrgHaKw?w=115&h=180&c=7&r=0&o=5&pid=1.7',
                appearances:35,
                goals: 17,
                // gpa:
                },

                {
                    firstname: 'Hamilton',
                    surname: 'Ricard',
                    dob: '12-01-1974',
                    nationality: 'Colombian',
                    club: 'Middlesbrough',
                    season: 1998,
                    league: 'epl',
                    img: 'https://th.bing.com/th/id/OIP.QWnSO65sXg8o1zyz-GWzywHaLH?w=133&h=200&c=7&r=0&o=5&pid=1.7',
                    appearances:36,
                    goals: 15,
                    // gpa:
                    },

    {
    firstname: 'Alan',
    surname: 'Shearer',
    dob: '13-08-1970',
    nationality: 'English',
    club: 'Newcastle United',
    season: 1998,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.V4Q11O7QTJ_vVOv57O-7PwHaJU?w=135&h=180&c=7&r=0&o=5&pid=1.7',
    appearances: 30,
    goals: 14,
    // gpa:
    },

    {
        firstname: 'Dion',
        surname: 'Dublin',
        dob: '22-04-1969',
        nationality: 'English',
        club: 'Coventry City and Aston Villa',
        season: 1998,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.A2VcBcVhghLFCQYPL809sAHaLH?w=185&h=278&c=7&r=0&o=5&pid=1.7',
        appearances:34 ,
        goals: 14,
        // gpa:
        },

        {
            firstname: 'Julian',
            surname: 'Joachim',
            dob: '20-09-1974',
            nationality: 'English',
            club: 'Coventry City',
            season: 1998,
            league: 'epl',
            img: 'https://th.bing.com/th/id/OIP.8xUCw2dFEE86xInAag8nLAAAAA?w=137&h=206&c=7&r=0&o=5&pid=1.7',
            appearances:36 ,
            goals: 14,
            // gpa:
            },

            {
                firstname: 'Robbie',
                surname: 'Fowler',
                dob: '09-02-1975',
                nationality: 'English',
                club: 'Liverpool',
                season: 1998,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.QXTNLL4fhlRaSvx4CIXN2AHaHj?w=183&h=187&c=7&r=0&o=5&pid=1.7',
                appearances: 25,
                goals: 14,
                // gpa:
                },

//1999
//epl

{
    firstname: 'Kevin',
    surname: 'Phillips',
    dob: '25-07-1973',
    nationality: 'English',
    club: 'Sunderland',
    season: 1999,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.Qua_o8mhaT0sqEpra_S7MwAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
    appearances: 36,
    goals: 30,
    // gpa:
    },
    {
        firstname: 'Alan',
        surname: 'Shearer',
        dob: '13-08-1970',
        nationality: 'English',
        club: 'Newcastle United',
        season: 1999,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.V4Q11O7QTJ_vVOv57O-7PwHaJU?w=135&h=180&c=7&r=0&o=5&pid=1.7',
        appearances: 37,
        goals: 23,
        // gpa:
        },

        {
            firstname: 'Dwight',
            surname: 'Yorke',
            dob: '03-11-1971',
            nationality: 'Trinidadian and Tobagonian',
            club: 'Manchester United',
            season: 1999,
            league: 'epl',
            img: 'https://th.bing.com/th/id/OIP.IVGBeBTr13zdU5qee83QlgHaK3?w=125&h=185&c=7&r=0&o=5&pid=1.7',
            appearances:32,
            goals: 20,
            // gpa:
            },

            {
                firstname: 'Andy',
                surname: 'Cole',
                dob: '15-10-1971',
                nationality: 'English',
                club: 'Manchester United',
                season: 1999,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.d0LgH4PuRQ_azNAGCN6fxAAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
                appearances:28,
                goals: 19,
                // gpa:
                },
                {
                    firstname: 'Michael',
                    surname: 'Bridges',
                    dob: '05-08-1978',
                    nationality: 'English',
                    club: 'Leeds United',
                    season: 1999,
                    league: 'epl',
                    img: 'https://th.bing.com/th/id/OIP.2c841uuCXRfOWqT_9OYVwQHaH5?w=162&h=180&c=7&r=0&o=5&pid=1.7',
                    appearances:34,
                    goals: 19,
                    // gpa:
                    },
                    {
                        firstname: 'Thierry',
                        surname: 'Henry',
                        dob: '17-08-1977',
                        nationality: 'French',
                        club: 'Arsenal',
                        season: 1999,
                        league: 'epl',
                        img: 'https://th.bing.com/th/id/OIP.zH-eLdIZp-xn_22CRg7I8wHaJ9?w=122&h=180&c=7&r=0&o=5&pid=1.7',
                        appearances:31,
                        goals: 17,
                        // gpa:
                        },
                        {
                            firstname: 'Paolo',
                            surname: 'Di Canio',
                            dob: '09-07-1968',
                            nationality: 'Italian',
                            club: 'West Ham United',
                            season: 1999,
                            league: 'epl',
                            img: 'https://th.bing.com/th/id/OIP.hKTLJqMdtZL8iEEI8_th2wHaJK?w=150&h=186&c=7&r=0&o=5&pid=1.7',
                            appearances:30,
                            goals: 16,
                            // gpa:
                            },
                            {
                                firstname: 'Chris',
                                surname: 'Armstrong',
                                dob: '19-06-1971',
                                nationality: 'English',
                                club: 'Tottenham Hotspur',
                                season: 1999,
                                league: 'epl',
                                img: 'https://th.bing.com/th/id/OIP.QwhLkgUxds6lSJu7IEYJpwHaJj?w=185&h=238&c=7&r=0&o=5&pid=1.7',
                                appearances:31 ,
                                goals: 14,
                                // gpa:
                                },
                                {
                                    firstname: 'Niall',
                                    surname: 'Quinn',
                                    dob: '06-10-1966',
                                    nationality: 'Irish',
                                    club: 'Sunderlnd',
                                    season: 1999,
                                    league: 'epl',
                                    img: 'https://th.bing.com/th/id/OIP.-HaSTsmQVsOpy9MzfhJTUwHaLF?w=122&h=182&c=7&r=0&o=5&pid=1.7',
                                    appearances:37 ,
                                    goals: 14,
                                    // gpa:
                                    },
                                    {
                                        firstname: 'Stefan',
                                        surname: 'Iversen',
                                        dob: '10-11-1976',
                                        nationality: 'Norwegian',
                                        club: 'Tottenham Hotspur',
                                        season: 1999,
                                        league: 'epl',
                                        img: 'https://th.bing.com/th/id/OIP.ApA5BLbH0h62so4fTe3fBAHaOG?w=181&h=345&c=7&r=0&o=5&pid=1.7',
                                        appearances:36 ,
                                        goals: 14,
                                        // gpa:
                                        },

//2000
//epl

{
    firstname: 'Jimmy Floyd',
    surname: 'Hasselbaink',
    dob: '27-03-1972',
    nationality: 'Dutch',
    club: 'Chelsea',
    season: 2000,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIF.NNIchJMT3RbT1ccyilgVRg?w=248&h=180&c=7&r=0&o=5&pid=1.7',
    appearances:35 ,
    goals: 23,
    // gpa:
    },

    {
        firstname: 'Marcus',
        surname: 'Stewart',
        dob: '07-11-1972',
        nationality: 'English',
        club: 'Ipswich Town',
        season: 2000,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.HhoGzgIy4ur5GwHgneiAZAAAAA?w=125&h=180&c=7&r=0&o=5&pid=1.7',
        appearances:34 ,
        goals: 19,
        // gpa:
        },
        {
            firstname: 'Mark',
            surname: 'Viduka',
            dob: '09-10-1975',
            nationality: 'Australian',
            club: 'Leeds United',
            season: 2000,
            league: 'epl',
            img: 'https://th.bing.com/th/id/OIP.mByAyVSOmn7I4tPXtq-jbQAAAA?w=126&h=180&c=7&r=0&o=5&pid=1.7',
            appearances:34 ,
            goals: 17,
            // gpa:
            },
            {
                firstname: 'Thierry',
                surname: 'Henry',
                dob: '17-08-1977',
                nationality: 'French',
                club: 'Arsenal',
                season: 2000,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.zH-eLdIZp-xn_22CRg7I8wHaJ9?w=122&h=180&c=7&r=0&o=5&pid=1.7',
                appearances:35,
                goals: 17,
                // gpa:
                },

                {
                    firstname: 'Michael',
                    surname: 'Owen',
                    dob: '14-12-1979',
                    nationality: 'English',
                    club: 'Liverpool',
                    season: 2000,
                    league: 'epl',
                    img: 'https://th.bing.com/th?id=OIF.9PgDPpRq%2f0RsIai2FtImiQ&w=184&h=180&c=7&r=0&o=5&pid=1.7',
                    appearances:28 ,
                    goals: 16,
                    // gpa:
                    },
                    {
                        firstname: 'Teddy',
                        surname: 'Sheringham',
                        dob: '02-04-1966',
                        nationality: 'English',
                        club: 'Manchester United',
                        season: 2000,
                        league: 'epl',
                        img: 'https://th.bing.com/th/id/OIP._RNFxVzbWDusSUbSWNk40wHaJX?w=154&h=184&c=7&r=0&o=5&pid=1.7',
                        appearances:29 ,
                        goals:15 ,
                        // gpa:
                        },
                        {
                            firstname: 'Emile',
                            surname: 'Heskey',
                            dob: '11-01-1978',
                            nationality: 'English',
                            club: 'Liverpool',
                            season: 2000,
                            league: 'epl',
                            img: 'https://th.bing.com/th/id/OIP.77rkqDEmm405Jx44yX1cdgHaIz?w=164&h=195&c=7&r=0&o=5&pid=1.7',
                            appearances:36 ,
                            goals:14 ,
                            // gpa:
                            },
                            {
                                firstname: 'Kevin',
                                surname: 'Phillips',
                                dob: '25-07-1973',
                                nationality: 'English',
                                club: 'Sunderland',
                                season: 2000,
                                league: 'epl',
                                img: 'https://th.bing.com/th/id/OIP.Qua_o8mhaT0sqEpra_S7MwAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
                                appearances: 34,
                                goals: 14,
                                // gpa:
                                },
                                {
                                    firstname: 'Alen',
                                    surname: 'Boksic',
                                    dob: '21-01-1970',
                                    nationality: 'Croatian',
                                    club: 'Middlesbrough',
                                    season: 2000,
                                    league: 'epl',
                                    img: 'https://th.bing.com/th/id/OIP.L4_THFg_pMvGi2nDtm3gMAHaJo?w=141&h=183&c=7&r=0&o=5&pid=1.7',
                                    appearances: 28,
                                    goals: 12,
                                    // gpa:
                                    },
                                    {
                                        firstname: 'Alan',
                                        surname: 'Smith',
                                        dob: '28-10-1980',
                                        nationality: 'English',
                                        club: 'Leeds United',
                                        season: 2000,
                                        league: 'epl',
                                        img: 'https://th.bing.com/th/id/OIP.TbSySUeo0sL-vPROcI6edQHaMO?w=118&h=195&c=7&r=0&o=5&pid=1.7',
                                        appearances: 33,
                                        goals: 11,
                                        // gpa:
                                        },
                                        {
                                            firstname: 'Frederic',
                                            surname: 'Kanoute',
                                            dob: '17-09-1977',
                                            nationality: 'French / Malian',
                                            club: 'West Ham United',
                                            season: 2000,
                                            league: 'epl',
                                            img: 'https://th.bing.com/th/id/OIP.61LO9BY1OER7j3FUQf-p5AHaGP?w=203&h=180&c=7&r=0&o=5&pid=1.7',
                                            appearances: 32,
                                            goals: 11,
                                            // gpa:
                                            },
                                            {
                                                firstname: 'Gustavo',
                                                surname: 'Poyet',
                                                dob: '15-11-1967',
                                                nationality: 'Uruguayan',
                                                club: 'Chelsea',
                                                season: 2000,
                                                league: 'epl',
                                                img: 'https://th.bing.com/th/id/OIP.RnLq9Tkij-jO40xqZqJCtgAAAA?w=121&h=180&c=7&r=0&o=5&pid=1.7',
                                                appearances: 30,
                                                goals: 11,
                                                // gpa:
                                                },
                                                {
                                                    firstname: 'James',
                                                    surname: 'Beattie',
                                                    dob: '27-02-1978',
                                                    nationality: 'English',
                                                    club: 'Southampton',
                                                    season: 2000,
                                                    league: 'epl',
                                                    img: 'https://th.bing.com/th/id/OIP.paZsrrUJdhNnEmmT8t46FAHaJT?w=142&h=180&c=7&r=0&o=5&pid=1.7',
                                                    appearances: 37,
                                                    goals: 11,
                                                    // gpa:
                                                    },
                                                {
                                                    firstname: 'Jonaton',
                                                    surname: 'Johansson',
                                                    dob: '16-08-1975',
                                                    nationality: 'Finnish',
                                                    club: 'Charlton Athletic',
                                                    season: 2000,
                                                    league: 'epl',
                                                    img: 'https://th.bing.com/th/id/OIP.JciorK4EAd-sEpDmnny6wQHaJ4?w=155&h=207&c=7&r=0&o=5&pid=1.7',
                                                    appearances: 31,
                                                    goals: 11,
                                                    // gpa:
                                                    },

//2001
//epl

{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2001,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.zH-eLdIZp-xn_22CRg7I8wHaJ9?w=122&h=180&c=7&r=0&o=5&pid=1.7',
    appearances:33,
    goals: 24,
    // gpa:
    },
    {
        firstname: 'Alan',
        surname: 'Shearer',
        dob: '13-08-1970',
        nationality: 'English',
        club: 'Newcastle United',
        season: 2001,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.V4Q11O7QTJ_vVOv57O-7PwHaJU?w=135&h=180&c=7&r=0&o=5&pid=1.7',
        appearances: 37,
        goals: 23,
        // gpa:
        },
        {
            firstname: 'Jimmy Floyd',
            surname: 'Hasselbaink',
            dob: '27-03-1972',
            nationality: 'Dutch',
            club: 'Chelsea',
            season: 2001,
            league: 'epl',
            img: 'https://th.bing.com/th/id/OIF.NNIchJMT3RbT1ccyilgVRg?w=248&h=180&c=7&r=0&o=5&pid=1.7',
            appearances:35 ,
            goals: 23,
            // gpa:
            },

            {
                firstname: 'Ruud',
                surname: 'Van Nistelrooy',
                dob: '01-07-1976',
                nationality: 'Dutch',
                club: 'Manchester United',
                season: 2001,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.DTeAHDqc1jWXQBMWGmUIDQHaLy?w=119&h=189&c=7&r=0&o=5&pid=1.7',
                appearances:32 ,
                goals: 23,
                // gpa:
                },

{                    
    firstname: 'Michael',
    surname: 'Owen',
    dob: '14-12-1979',
    nationality: 'English',
    club: 'Liverpool',
    season: 2001,
    league: 'epl',
    img: 'https://th.bing.com/th?id=OIF.9PgDPpRq%2f0RsIai2FtImiQ&w=184&h=180&c=7&r=0&o=5&pid=1.7',
    appearances:29 ,
    goals: 19,
    // gpa:
    },
    {
        firstname: 'Ole Gunnar',
        surname: 'Solskjær',
        dob: '26-02-1973',
        nationality: 'Norwegian',
        club: 'Manchester United',
        season: 2001,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.x0hwff2JjKEWqcb3fKOpdgHaHa?w=160&h=180&c=7&r=0&o=5&pid=1.7',
        appearances:30 ,
        goals: 17,
        // gpa:
        },
        {
            firstname: 'Robbie',
            surname: 'Fowler',
            dob: '09-02-1975',
            nationality: 'English',
            club: 'Liverpool and Leeds United',
            season: 2001,
            league: 'epl',
            img: 'https://th.bing.com/th/id/OIP.QXTNLL4fhlRaSvx4CIXN2AHaHj?w=183&h=187&c=7&r=0&o=5&pid=1.7',
            appearances: 32,
            goals: 15,
            // gpa:
            },
        {
            firstname: 'Eidur',
            surname: 'Gudjohnson',
            dob: '15-09-1978',
            nationality: 'Icelandic',
            club: 'Chelsea',
            season: 2001,
            league: 'epl',
            img: 'https://th.bing.com/th/id/OIP.s8S1-oFISSImSkxa1NepUAHaGb?w=199&h=180&c=7&r=0&o=5&pid=1.7',
            appearances:32 ,
            goals: 14,
            // gpa:
            },
            {
                firstname: 'Marians',
                surname: 'Pahars',
                dob: '05-08-1976',
                nationality: 'Latvian',
                club: 'Southampton',
                season: 2001,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.qms45GsxqysBwDMmY4LIsQHaKF?w=115&h=180&c=7&r=0&o=5&pid=1.7',
                appearances:36 ,
                goals: 14,
                // gpa:
                },
                {
                    firstname: 'Andy',
                    surname: 'Cole',
                    dob: '15-10-1971',
                    nationality: 'English',
                    club: 'Manchester United and Blackburn Rovers',
                    season: 2001,
                    league: 'epl',
                    img: 'https://th.bing.com/th/id/OIP.d0LgH4PuRQ_azNAGCN6fxAAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
                    appearances:26,
                    goals: 13,
                    // gpa:
                    },

//2002
//epl

{
    firstname: 'Ruud',
    surname: 'Van Nistelrooy',
    dob: '01-07-1976',
    nationality: 'Dutch',
    club: 'Manchester United',
    season: 2002,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.DTeAHDqc1jWXQBMWGmUIDQHaLy?w=119&h=189&c=7&r=0&o=5&pid=1.7',
    appearances:34 ,
    goals: 25,
    // gpa:
    },

{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2002,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.zH-eLdIZp-xn_22CRg7I8wHaJ9?w=122&h=180&c=7&r=0&o=5&pid=1.7',
    appearances:37,
    goals: 24,
    // gpa:
    },
    {
        firstname: 'James',
        surname: 'Beattie',
        dob: '27-02-1978',
        nationality: 'English',
        club: 'Southampton',
        season: 2002,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.paZsrrUJdhNnEmmT8t46FAHaJT?w=142&h=180&c=7&r=0&o=5&pid=1.7',
        appearances: 38,
        goals: 23,
        // gpa:
        },
        {
            firstname: 'Mark',
            surname: 'Viduka',
            dob: '09-10-1975',
            nationality: 'Australian',
            club: 'Leeds United',
            season: 2002,
            league: 'epl',
            img: 'https://th.bing.com/th/id/OIP.mByAyVSOmn7I4tPXtq-jbQAAAA?w=126&h=180&c=7&r=0&o=5&pid=1.7',
            appearances:33 ,
            goals: 20,
            // gpa:
            },
            {
                firstname: 'Michael',
                surname: 'Owen',
                dob: '14-12-1979',
                nationality: 'English',
                club: 'Liverpool',
                season: 2002,
                league: 'epl',
                img: 'https://th.bing.com/th?id=OIF.9PgDPpRq%2f0RsIai2FtImiQ&w=184&h=180&c=7&r=0&o=5&pid=1.7',
                appearances:35 ,
                goals: 19,
                // gpa:
                },
                {
                    firstname: 'Alan',
                    surname: 'Shearer',
                    dob: '13-08-1970',
                    nationality: 'English',
                    club: 'Newcastle United',
                    season: 2002,
                    league: 'epl',
                    img: 'https://th.bing.com/th/id/OIP.V4Q11O7QTJ_vVOv57O-7PwHaJU?w=135&h=180&c=7&r=0&o=5&pid=1.7',
                    appearances: 35,
                    goals: 17,
                    // gpa:
                    },
                    {
                        firstname: 'Gianfranco',
                        surname: 'Zola',
                        dob: '05-07-1966',
                        nationality: 'English',
                        club: 'Chelsea',
                        season: 2002,
                        league: 'epl',
                        img: 'https://th.bing.com/th/id/OIP.G5NfA04PK5XrNSnMjfKdRQHaFN?w=256&h=180&c=7&r=0&o=5&pid=1.7',
                        appearances: 38,
                        goals: 14,
                        // gpa:
                        },
                        {
                            firstname: 'Harry',
                            surname: 'Kewell',
                            dob: '22-09-1978',
                            nationality: 'Australian',
                            club: 'Leeds United',
                            season: 2002,
                            league: 'epl',
                            img: 'https://th.bing.com/th/id/OIP.ZVMNbbfPeiZIPiCIgWFrGwAAAA?w=185&h=266&c=7&r=0&o=5&pid=1.7',
                            appearances: 31,
                            goals: 14,
                            // gpa:
                            },
                            {
                                firstname: 'Nicolas',
                                surname: 'Anelka',
                                dob: '14-03-1979',
                                nationality: 'French',
                                club: 'Manchester City',
                                season: 2002,
                                league: 'epl',
                                img: 'https://th.bing.com/th/id/OIP.wi0IxmqIyvSzVaVIvLlnawDZEs?w=185&h=256&c=7&r=0&o=5&pid=1.7',
                                appearances:38,
                                goals: 14,
                                // gpa:
                                },
                                {
                                    firstname: 'Paul',
                                    surname: 'Scholes',
                                    dob: '16-11-1974',
                                    nationality: 'English',
                                    club: 'Manchester United',
                                    season: 2002,
                                    league: 'epl',
                                    img: 'https://th.bing.com/th/id/OIP.mZbBuflXGnY_tXbZWUrSnAHaFl?w=228&h=180&c=7&r=0&o=5&pid=1.7',
                                    appearances:33,
                                    goals: 14,
                                    // gpa:
                                    },
                                    {
                                        firstname: 'Robbie',
                                        surname: 'Keane',
                                        dob: '08-07-1980',
                                        nationality: 'Irish',
                                        club: 'Leeds United and Tottenham Hotspur',
                                        season: 2002,
                                        league: 'epl',
                                        img: 'https://th.bing.com/th/id/OIP.5-hKdNaS0K0mujKdEcmMHwHaMC?w=115&h=180&c=7&r=0&o=5&pid=1.7',
                                        appearances:32,
                                        goals: 14,
                                        // gpa:
                                        },
                                        {
                                            firstname: 'Robert',
                                            surname: 'Pires',
                                            dob: '29-10-1973',
                                            nationality: 'French',
                                            club: 'Arsenal',
                                            season: 2002,
                                            league: 'epl',
                                            img: 'https://th.bing.com/th/id/OIP.rdplSXhHk9AEBvg6g2lvoAAAAA?w=125&h=180&c=7&r=0&o=5&pid=1.7',
                                            appearances:26,
                                            goals: 14,
                                            // gpa:
                                            },

//2003
//epl

{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2003,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.zH-eLdIZp-xn_22CRg7I8wHaJ9?w=122&h=180&c=7&r=0&o=5&pid=1.7',
    appearances:37,
    goals: 30,
    // gpa:
    },
    {
        firstname: 'Alan',
        surname: 'Shearer',
        dob: '13-08-1970',
        nationality: 'English',
        club: 'Newcastle United',
        season: 2003,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.V4Q11O7QTJ_vVOv57O-7PwHaJU?w=135&h=180&c=7&r=0&o=5&pid=1.7',
        appearances: 37,
        goals: 22,
        // gpa:
        },
        {
            firstname: 'Louis',
            surname: 'Saha',
            dob: '08-08-1978',
            nationality: 'French',
            club: 'Fulham and Manchester United',
            season: 2003,
            league: 'epl',
            img: 'https://th.bing.com/th/id/OIP.rvOrdoKZu4k7nvf57qukpgHaLM?w=116&h=180&c=7&r=0&o=5&pid=1.7',
            appearances:33 ,
            goals: 20,
            // gpa:
            },
            {
                firstname: 'Ruud',
                surname: 'Van Nistelrooy',
                dob: '01-07-1976',
                nationality: 'Dutch',
                club: 'Manchester United',
                season: 2003,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.DTeAHDqc1jWXQBMWGmUIDQHaLy?w=119&h=189&c=7&r=0&o=5&pid=1.7',
                appearances:32 ,
                goals: 20,
                // gpa:
                },
                {
                    firstname: 'Mikael',
                    surname: 'Forsell',
                    dob: '15-03-1981',
                    nationality: 'Finnish',
                    club: 'Birmingham City',
                    season: 2003,
                    league: 'epl',
                    img: 'https://th.bing.com/th/id/OIP.wSfCc67A8HVPTJBrIogajgAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
                    appearances:32 ,
                    goals: 17,
                    // gpa:
                    },
                    {
                        firstname: 'Juan Pablo',
                        surname: 'Angel',
                        dob: '24-10-1975',
                        nationality: 'Colombian',
                        club: 'Aston Villa',
                        season: 2003,
                        league: 'epl',
                        img: 'https://th.bing.com/th/id/OIP.ufmn1Jplzg4vTW9pPoJblgHaLt?w=185&h=293&c=7&r=0&o=5&pid=1.7',
                        appearances:33 ,
                        goals: 16,
                        // gpa:
                        },
                        {
                            firstname: 'Michael',
                            surname: 'Owen',
                            dob: '14-12-1979',
                            nationality: 'English',
                            club: 'Liverpool',
                            season: 2003,
                            league: 'epl',
                            img: 'https://th.bing.com/th?id=OIF.9PgDPpRq%2f0RsIai2FtImiQ&w=184&h=180&c=7&r=0&o=5&pid=1.7',
                            appearances:29 ,
                            goals: 16,
                            // gpa:
                            },
                            {
                                firstname: 'Nicolas',
                                surname: 'Anelka',
                                dob: '14-03-1979',
                                nationality: 'French',
                                club: 'Manchester City',
                                season: 2003,
                                league: 'epl',
                                img: 'https://th.bing.com/th/id/OIP.wi0IxmqIyvSzVaVIvLlnawDZEs?w=185&h=256&c=7&r=0&o=5&pid=1.7',
                                appearances:32,
                                goals: 16,
                                // gpa:
                                },
                            {
                                firstname: 'Yakubu',
                                surname: 'Ayegbeni',
                                dob: '22-11-1982',
                                nationality: 'Nigerian',
                                club: 'Portsmouth',
                                season: 2003,
                                league: 'epl',
                                img: 'https://th.bing.com/th/id/OIP.TUez5pJsoyKcVlVlxh5vUwHaFj?w=199&h=187&c=7&r=0&o=5&pid=1.7',
                                appearances:37,
                                goals: 16,
                                // gpa:
                                },
                                {
                                    firstname: 'James',
                                    surname: 'Beattie',
                                    dob: '27-02-1978',
                                    nationality: 'English',
                                    club: 'Southampton',
                                    season: 2003,
                                    league: 'epl',
                                    img: 'https://th.bing.com/th/id/OIP.paZsrrUJdhNnEmmT8t46FAHaJT?w=142&h=180&c=7&r=0&o=5&pid=1.7',
                                    appearances: 37,
                                    goals: 14,
                                    // gpa:
                                    },
                                    {
                                        firstname: 'Robbie',
                                        surname: 'Keane',
                                        dob: '08-07-1980',
                                        nationality: 'Irish',
                                        club: 'Tottenham Hotspur',
                                        season: 2003,
                                        league: 'epl',
                                        img: 'https://th.bing.com/th/id/OIP.5-hKdNaS0K0mujKdEcmMHwHaMC?w=115&h=180&c=7&r=0&o=5&pid=1.7',
                                        appearances:34,
                                        goals: 14,
                                        // gpa:
                                        },
                                        {
                                            firstname: 'Robert',
                                            surname: 'Pires',
                                            dob: '29-10-1973',
                                            nationality: 'French',
                                            club: 'Arsenal',
                                            season: 2003,
                                            league: 'epl',
                                            img: 'https://th.bing.com/th/id/OIP.rdplSXhHk9AEBvg6g2lvoAAAAA?w=125&h=180&c=7&r=0&o=5&pid=1.7',
                                            appearances:36,
                                            goals: 14,
                                            // gpa:
                                            },

//2004
//epl                                        

{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2004,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.zH-eLdIZp-xn_22CRg7I8wHaJ9?w=122&h=180&c=7&r=0&o=5&pid=1.7',
    appearances:32,
    goals: 25,
    // gpa:
    },
    {
        firstname: 'Andrew',
        surname: 'Johnson',
        dob: '10-02-1981',
        nationality: 'English',
        club: 'Crystal Palace',
        season: 2004,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.15QzKSeaX9k0hJSeaFpCXAHaEK?w=282&h=180&c=7&r=0&o=5&pid=1.7',
        appearances:37,
        goals: 21,
        // gpa:
        },
        {
            firstname: 'Robert',
            surname: 'Pires',
            dob: '29-10-1973',
            nationality: 'French',
            club: 'Arsenal',
            season: 2004,
            league: 'epl',
            img: 'https://th.bing.com/th/id/OIP.rdplSXhHk9AEBvg6g2lvoAAAAA?w=125&h=180&c=7&r=0&o=5&pid=1.7',
            appearances:33,
            goals: 14,
            // gpa:
            },
            {
                firstname: 'Frank',
                surname: 'Lampard',
                dob: '20-06-1978',
                nationality: 'English',
                club: 'Chelsea',
                season: 2004,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.XF_ASjrEPf9CqYF1Jm4TdgHaE7?w=152&h=180&c=7&r=0&o=5&pid=1.7',
                appearances:38,
                goals: 13,
                // gpa:
                },
            {
                firstname: 'Jermaine',
                surname: 'Defoe',
                dob: '07-10-1982',
                nationality: 'English',
                club: 'Tottenham Hotspur',
                season: 2004,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.27BY-oRpDfsCFVmc3Qi4NgHaHU?w=185&h=183&c=7&r=0&o=5&pid=1.7',
                appearances:35,
                goals: 13,
                // gpa:
                },
                {
                    firstname: 'Jimmy Floyd',
                    surname: 'Hasselbaink',
                    dob: '27-03-1972',
                    nationality: 'Dutch',
                    club: 'Middlesbrough',
                    season: 2004,
                    league: 'epl',
                    img: 'https://th.bing.com/th/id/OIP.xin-ERmgy7TT-2iwhemN6gHaLG?w=185&h=278&c=7&r=0&o=5&pid=1.7',
                    appearances:36 ,
                    goals: 13,
                    // gpa:
                    },
                    {
                        firstname: 'Yakubu',
                        surname: 'Ayegbeni',
                        dob: '22-11-1982',
                        nationality: 'Nigerian',
                        club: 'Portsmouth',
                        season: 2004,
                        league: 'epl',
                        img: 'https://th.bing.com/th/id/OIP.TUez5pJsoyKcVlVlxh5vUwHaFj?w=199&h=187&c=7&r=0&o=5&pid=1.7',
                        appearances:30,
                        goals: 13,
                        // gpa:
                        },
                        {
                            firstname: 'Andy',
                            surname: 'Cole',
                            dob: '15-10-1971',
                            nationality: 'English',
                            club: 'Fulham',
                            season: 2004,
                            league: 'epl',
                            img: 'https://th.bing.com/th/id/OIP.zmzvgBUcL4uqJLP828XKpgAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7',
                            appearances:31,
                            goals: 12,
                            // gpa:
                            },
                            {
                                firstname: 'Eidur',
                                surname: 'Gudjohnson',
                                dob: '15-09-1978',
                                nationality: 'Icelandic',
                                club: 'Chelsea',
                                season: 2004,
                                league: 'epl',
                                img: 'https://th.bing.com/th/id/OIP.s8S1-oFISSImSkxa1NepUAHaGb?w=199&h=180&c=7&r=0&o=5&pid=1.7',
                                appearances: 37,
                                goals: 12,
                                // gpa:
                                },
                                {
                                    firstname: 'Peter',
                                    surname: 'Crouch',
                                    dob: '30-01-1981',
                                    nationality: 'English',
                                    club: 'Southampton',
                                    season: 2004,
                                    league: 'epl',
                                    img: 'https://th.bing.com/th/id/OIP.YWoDrx4JUQOWw_AZf-1QTQHaJ2?w=117&h=180&c=7&r=0&o=5&pid=1.7',
                                    appearances:27 ,
                                    goals: 12,
                                    // gpa:
                                    },

//2005
//epl

{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2005,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.zH-eLdIZp-xn_22CRg7I8wHaJ9?w=122&h=180&c=7&r=0&o=5&pid=1.7',
    appearances:32,
    goals: 27,
    // gpa:
    },
    {
        firstname: 'Ruud',
        surname: 'Van Nistelrooy',
        dob: '01-07-1976',
        nationality: 'Dutch',
        club: 'Manchester United',
        season: 2005,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.DTeAHDqc1jWXQBMWGmUIDQHaLy?w=119&h=189&c=7&r=0&o=5&pid=1.7',
        appearances:35 ,
        goals: 21,
        // gpa:
        },
        {
            firstname: 'Darren',
            surname: 'Bent',
            dob: '06-02-1984',
            nationality: 'English',
            club: 'Charlton Athletic',
            season: 2005,
            league: 'epl',
            img: 'https://th.bing.com/th/id/OIP.JLowxpGMZPz_ix-wHyG3PwHaJE?w=132&h=180&c=7&r=0&o=5&pid=1.7',
            appearances:36 ,
            goals: 18,
            // gpa:
            },
            {
                firstname: 'Frank',
                surname: 'Lampard',
                dob: '20-06-1978',
                nationality: 'English',
                club: 'Chelsea',
                season: 2005,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.XF_ASjrEPf9CqYF1Jm4TdgHaE7?w=152&h=180&c=7&r=0&o=5&pid=1.7',
                appearances:35,
                goals: 16,
                // gpa:
                },
                {
                    firstname: 'Robbie',
                    surname: 'Keane',
                    dob: '08-07-1980',
                    nationality: 'Irish',
                    club: 'Tottenham Hotspur',
                    season: 2005,
                    league: 'epl',
                    img: 'https://th.bing.com/th/id/OIP.5-hKdNaS0K0mujKdEcmMHwHaMC?w=115&h=180&c=7&r=0&o=5&pid=1.7',
                    appearances:36,
                    goals: 16,
                    // gpa:
                    },
                    {
                        firstname: 'Wayne',
                        surname: 'Rooney',
                        dob: '24-10-1985',
                        nationality: 'English',
                        club: 'Manchester United',
                        season: 2005,
                        league: 'epl',
                        img: 'https://th.bing.com/th/id/OIP.Dj2ZbCPTRpEP64z3aKCqHQHaJY?w=160&h=184&c=7&r=0&o=5&pid=1.7',
                        appearances:36,
                        goals: 16,
                        // gpa:
                        },
                        {
                            firstname: 'Marlon',
                            surname: 'Harewood',
                            dob: '25-08-1979',
                            nationality: 'English',
                            club: 'West Ham United',
                            season: 2005,
                            league: 'epl',
                            img: 'https://th.bing.com/th/id/OIP._fNSwFyh-YbMNEC7Qd_b1wHaLT?w=115&h=180&c=7&r=0&o=5&pid=1.7',
                            appearances:37,
                            goals: 14,
                            // gpa:
                            },
                            {
                                firstname: 'Craig',
                                surname: 'Bellamy',
                                dob: '13-07-1979',
                                nationality: 'Welsh',
                                club: 'Blackburn Rovers',
                                season: 2005,
                                league: 'epl',
                                img: 'https://th.bing.com/th/id/OIP.oBEs7vammeMNRvajDvL-NwAAAA?w=185&h=296&c=7&r=0&o=5&pid=1.7',
                                appearances:27,
                                goals: 13,
                                // gpa:
                                },
                                {
                                    firstname: 'Yakubu',
                                    surname: 'Ayegbeni',
                                    dob: '22-11-1982',
                                    nationality: 'Nigerian',
                                    club: 'Middlesbrough',
                                    season: 2005,
                                    league: 'epl',
                                    img: 'https://th.bing.com/th/id/OIP.v5flKlTwSnDBaD7Sm-q-5wHaKd?w=132&h=187&c=7&r=0&o=5&pid=1.7',
                                    appearances:34,
                                    goals: 13,
                                    // gpa:
                                    },
                                    {
                                        firstname: 'Didier',
                                        surname: 'Drogba',
                                        dob: '11-03-1978',
                                        nationality: 'Ivorian',
                                        club: 'Chelsea',
                                        season: 2005,
                                        league: 'epl',
                                        img: 'https://th.bing.com/th/id/OIP.7mfSwg2PWP055bDmUhAemgHaIX?w=164&h=184&c=7&r=0&o=5&pid=1.7',
                                        appearances:29,
                                        goals: 12,
                                        // gpa:
                                        },
                                        {
                                            firstname: 'Henri',
                                            surname: 'Camara',
                                            dob: '10-05-1977',
                                            nationality: 'Senegalese',
                                            club: 'Wigan Athletic',
                                            season: 2005,
                                            league: 'epl',
                                            img: 'https://th.bing.com/th/id/OIP.0zADSm8wCSTq5Rr0Db6dDwAAAA?w=129&h=188&c=7&r=0&o=5&pid=1.7',
                                            appearances:29,
                                            goals: 12,
                                            // gpa:
                                            },


//2006
//epl

{
    firstname: 'Didier',
    surname: 'Drogba',
    dob: '11-03-1978',
    nationality: 'Ivorian',
    club: 'Chelsea',
    season: 2006,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.7mfSwg2PWP055bDmUhAemgHaIX?w=164&h=184&c=7&r=0&o=5&pid=1.7',
    appearances:36,
    goals: 20,
    // gpa:
    },
    {
        firstname: 'Benni',
        surname: 'McCarthy',
        dob: '12-11-1977',
        nationality: 'South African',
        club: 'Blackburn Rovers',
        season: 2006,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.9TEgkMoB-ZoZMJy2tDz1ggHaKV?w=115&h=180&c=7&r=0&o=5&pid=1.7',
        appearances:36,
        goals: 18,
        // gpa:
        },
        {
            firstname: 'Cristiano',
            surname: 'Ronaldo',
            dob: '05-02-1985',
            nationality: 'Portugese',
            club: 'Manchester United',
            season: 2006,
            league: 'epl',
            img: 'https://th.bing.com/th/id/OIP.l7XIWpGCYexKJ9GhkcReFgHaKQ?w=120&h=180&c=7&r=0&o=5&pid=1.7',
            appearances:34,
            goals: 17,
            // gpa:
            },
            {
                firstname: 'Mark',
                surname: 'Viduka',
                dob: '09-10-1975',
                nationality: 'Australian',
                club: 'Middlesbrough',
                season: 2006,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.XImzgp0J05hz6vVgdAM80wHaK0?w=185&h=271&c=7&r=0&o=5&pid=1.7',
                appearances:29 ,
                goals: 14,
                // gpa:
                },
                {
                    firstname: 'Wayne',
                    surname: 'Rooney',
                    dob: '24-10-1985',
                    nationality: 'English',
                    club: 'Manchester United',
                    season: 2006,
                    league: 'epl',
                    img: 'https://th.bing.com/th/id/OIP.Dj2ZbCPTRpEP64z3aKCqHQHaJY?w=160&h=184&c=7&r=0&o=5&pid=1.7',
                    appearances:35,
                    goals: 14,
                    // gpa:
                    },
                    {
                        firstname: 'Darren',
                        surname: 'Bent',
                        dob: '06-02-1984',
                        nationality: 'English',
                        club: 'Charlton Athletic',
                        season: 2006,
                        league: 'epl',
                        img: 'https://th.bing.com/th/id/OIP.JLowxpGMZPz_ix-wHyG3PwHaJE?w=132&h=180&c=7&r=0&o=5&pid=1.7',
                        appearances:32 ,
                        goals: 13,
                        // gpa:
                        },
                        {
                            firstname: 'Kevin',
                            surname: 'Doyle',
                            dob: '18-09-1983',
                            nationality: 'Irish',
                            club: 'Reading',
                            season: 2006,
                            league: 'epl',
                            img: '',
                            appearances:32 ,
                            goals: 13,
                            // gpa:
                            },
                            {
                                firstname: 'Dimitar',
                                surname: 'Berbatov',
                                dob: '30-01-1981',
                                nationality: 'Bulgarian',
                                club: 'Tottenham Hostspur',
                                season: 2006,
                                league: 'epl',
                                img: '',
                                appearances:33 ,
                                goals: 12,
                                // gpa:
                                },
                                {
                                    firstname: 'Dirk',
                                    surname: 'Kuyt',
                                    dob: '22-07-1980',
                                    nationality: 'Dutch',
                                    club: 'Liverpool',
                                    season: 2006,
                                    league: 'epl',
                                    img: '',
                                    appearances:34 ,
                                    goals: 12,
                                    // gpa:
                                    },
                                    {
                                        firstname: 'Yakubu',
                                        surname: 'Ayegbeni',
                                        dob: '22-11-1982',
                                        nationality: 'Nigerian',
                                        club: 'Middlesbrough',
                                        season: 2006,
                                        league: 'epl',
                                        img: 'https://th.bing.com/th/id/OIP.v5flKlTwSnDBaD7Sm-q-5wHaKd?w=132&h=187&c=7&r=0&o=5&pid=1.7',
                                        appearances:37,
                                        goals: 12,
                                        // gpa:
                                        },


//2007
//epl

{
    firstname: 'Cristiano',
    surname: 'Ronaldo',
    dob: '05-02-1985',
    nationality: 'Portugese',
    club: 'Manchester United',
    season: 2007,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.l7XIWpGCYexKJ9GhkcReFgHaKQ?w=120&h=180&c=7&r=0&o=5&pid=1.7',
    appearances:34,
    goals: 31,
    // gpa:
    },
    {
        firstname: 'Emmanuel',
        surname: 'Adebayor',
        dob: '22-02-1984',
        nationality: 'Togolgese',
        club: 'Arsenal',
        season: 2007,
        league: 'epl',
        img: '',
        appearances:36,
        goals: 24,
        // gpa:
        },
        {
            firstname: 'Fernando',
            surname: 'Torres',
            dob: '20-03-1984',
            nationality: 'Spanish',
            club: 'Liverpool',
            season: 2007,
            league: 'epl',
            img: '',
            appearances:33,
            goals: 24,
            // gpa:
            },
            {
                firstname: 'Roque',
                surname: 'Santa Cruz',
                dob: '16-08-1981',
                nationality: 'Paraguayan',
                club: 'Blackburn Rovers',
                season: 2007,
                league: 'epl',
                img: '',
                appearances:37,
                goals: 19,
                // gpa:
                },
            {
                firstname: 'Benjani',
                surname: 'Mwaruwari',
                dob: '13-08-1978',
                nationality: 'Zimbabwean',
                club: 'Portsmouth and Manchester City',
                season: 2007,
                league: 'epl',
                img: '',
                appearances:36,
                goals: 15,
                // gpa:
                },
                {
                    firstname: 'Dimitar',
                    surname: 'Berbatov',
                    dob: '30-01-1981',
                    nationality: 'Bulgarian',
                    club: 'Tottenham Hostspurs and Manchester United',
                    season: 2007,
                    league: 'epl',
                    img: '',
                    appearances:36 ,
                    goals: 15,
                    // gpa:
                    },
                    {
                        firstname: 'Robbie',
                        surname: 'Keane',
                        dob: '08-07-1980',
                        nationality: 'Irish',
                        club: 'Tottenham Hotspur',
                        season: 2007,
                        league: 'epl',
                        img: 'https://th.bing.com/th/id/OIP.5-hKdNaS0K0mujKdEcmMHwHaMC?w=115&h=180&c=7&r=0&o=5&pid=1.7',
                        appearances:36,
                        goals: 15,
                        // gpa:
                        },
                        {
                            firstname: 'Yakubu',
                            surname: 'Ayegbeni',
                            dob: '22-11-1982',
                            nationality: 'Nigerian',
                            club: 'Middlesbrough and Everton',
                            season: 2007,
                            league: 'epl',
                            img: 'https://th.bing.com/th/id/OIP.ggv2l_6Ff2__szI6ohMDugAAAA?w=132&h=182&c=7&r=0&o=5&pid=1.7',
                            appearances:31,
                            goals: 19,
                            // gpa:
                            },
                            {
                                firstname: 'Carlos',
                                surname: 'Tevez',
                                dob: '05-02-1984',
                                nationality: 'Argentinian',
                                club: 'Manchester United',
                                season: 2007,
                                league: 'epl',
                                img: '',
                                appearances:34,
                                goals: 14,
                                // gpa:
                                },
                                {
                                    firstname: 'John',
                                    surname: 'Carew',
                                    dob: '05-09-1979',
                                    nationality: 'Norwegian',
                                    club: 'Aston Villa',
                                    season: 2007,
                                    league: 'epl',
                                    img: '',
                                    appearances:32,
                                    goals: 13,
                                    // gpa:
                                    },

//2008
//epl
                
{
    firstname: 'Nicolas',
    surname: 'Anelka',
    dob: '14-03-1979',
    nationality: 'French',
    club: 'Chelsea',
    season: 2008,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.maVIwCMRXiglI1Ca_NWBfgHaIX?w=185&h=209&c=7&r=0&o=5&pid=1.7',
    appearances:37,
    goals: 19,
    // gpa:
    },
    {
        firstname: 'Cristiano',
        surname: 'Ronaldo',
        dob: '05-02-1985',
        nationality: 'Portugese',
        club: 'Manchester United',
        season: 2008,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.l7XIWpGCYexKJ9GhkcReFgHaKQ?w=120&h=180&c=7&r=0&o=5&pid=1.7',
        appearances:33,
        goals: 18,
        // gpa:
        },
        {
            firstname: 'Steven',
            surname: 'Gerrard',
            dob: '30-05-1980',
            nationality: 'English',
            club: 'Liverpool',
            season: 2008,
            league: 'epl',
            img: '',
            appearances:31,
            goals: 16,
            // gpa:
            },
            {
                firstname: 'Robinho',
                surname: 'Robinho',
                dob: '21-05-1984',
                nationality: 'Brazilian',
                club: 'Manchester City',
                season: 2008,
                league: 'epl',
                img: '',
                appearances:31,
                goals: 14,
                // gpa:
                },
                {
                    firstname: 'Fernando',
                    surname: 'Torres',
                    dob: '20-03-1984',
                    nationality: 'Spanish',
                    club: 'Liverpool',
                    season: 2008,
                    league: 'epl',
                    img: '',
                    appearances:24,
                    goals: 14,
                    // gpa:
                    },
                    {
                        firstname: 'Gabriel',
                        surname: 'Agbonlahor',
                        dob: '13-10-1986',
                        nationality: 'English',
                        club: 'Aston Villa',
                        season: 2008,
                        league: 'epl',
                        img: '',
                        appearances:36,
                        goals: 12,
                        // gpa:
                        },
                        {
                            firstname: 'Darren',
                            surname: 'Bent',
                            dob: '06-02-1984',
                            nationality: 'English',
                            club: 'Tottenham Hotspur',
                            season: 2008,
                            league: 'epl',
                            img: 'https://th.bing.com/th/id/OIP.l3dJkLdlAOlEa6-bFyYOVAHaKy?w=137&h=199&c=7&r=0&o=5&pid=1.7',
                            appearances:33 ,
                            goals: 12,
                            // gpa:
                            },
                            {
                                firstname: 'Dirk',
                                surname: 'Kuyt',
                                dob: '22-07-1980',
                                nationality: 'Dutch',
                                club: 'Liverpool',
                                season: 2008,
                                league: 'epl',
                                img: '',
                                appearances:38 ,
                                goals: 12,
                                // gpa:
                                },
                                {
                                    firstname: 'Frank',
                                    surname: 'Lampard',
                                    dob: '20-06-1978',
                                    nationality: 'English',
                                    club: 'Chelsea',
                                    season: 2008,
                                    league: 'epl',
                                    img: 'https://th.bing.com/th/id/OIP.XF_ASjrEPf9CqYF1Jm4TdgHaE7?w=152&h=180&c=7&r=0&o=5&pid=1.7',
                                    appearances:37,
                                    goals: 12,
                                    // gpa:
                                    },
                                    {
                                        firstname: 'Kevin',
                                        surname: 'Davies',
                                        dob: '26-03-1977',
                                        nationality: 'English',
                                        club: 'Bolton Wanderers',
                                        season: 2008,
                                        league: 'epl',
                                        img: '',
                                        appearances:38,
                                        goals: 12,
                                        // gpa:
                                        },
                                        {
                                            firstname: 'Wayne',
                                            surname: 'Rooney',
                                            dob: '24-10-1985',
                                            nationality: 'English',
                                            club: 'Manchester United',
                                            season: 2008,
                                            league: 'epl',
                                            img: 'https://th.bing.com/th/id/OIP.Dj2ZbCPTRpEP64z3aKCqHQHaJY?w=160&h=184&c=7&r=0&o=5&pid=1.7',
                                            appearances:30,
                                            goals: 12,
                                            // gpa:
                                            },

//2009
//epl

{
    firstname: 'Didier',
    surname: 'Drogba',
    dob: '11-03-1978',
    nationality: 'Ivorian',
    club: 'Chelsea',
    season: 2009,
    league: 'epl',
    img: 'https://th.bing.com/th/id/OIP.7mfSwg2PWP055bDmUhAemgHaIX?w=164&h=184&c=7&r=0&o=5&pid=1.7',
    appearances:32,
    goals: 29,
    // gpa:
    },
    {
        firstname: 'Wayne',
        surname: 'Rooney',
        dob: '24-10-1985',
        nationality: 'English',
        club: 'Manchester United',
        season: 2009,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.Dj2ZbCPTRpEP64z3aKCqHQHaJY?w=160&h=184&c=7&r=0&o=5&pid=1.7',
        appearances:32,
        goals: 26,
        // gpa:
        },
    {
        firstname: 'Darren',
        surname: 'Bent',
        dob: '06-02-1984',
        nationality: 'English',
        club: 'Sunderland',
        season: 2009,
        league: 'epl',
        img: 'https://th.bing.com/th/id/OIP.fNodc74iXnSWQGlDtyxPWAHaK3?w=185&h=271&c=7&r=0&o=5&pid=1.7',
        appearances:38 ,
        goals: 24,
        // gpa:
        },
        {
            firstname: 'Carlos',
            surname: 'Tevez',
            dob: '05-02-1984',
            nationality: 'Argentinian',
            club: 'Manchester City',
            season: 2009,
            league: 'epl',
            img: '',
            appearances:35,
            goals: 23,
            // gpa:
            },
            {
                firstname: 'Frank',
                surname: 'Lampard',
                dob: '20-06-1978',
                nationality: 'English',
                club: 'Chelsea',
                season: 2009,
                league: 'epl',
                img: 'https://th.bing.com/th/id/OIP.XF_ASjrEPf9CqYF1Jm4TdgHaE7?w=152&h=180&c=7&r=0&o=5&pid=1.7',
                appearances:36,
                goals: 22,
                // gpa:
                },
                {
                    firstname: 'Fernando',
                    surname: 'Torres',
                    dob: '20-03-1984',
                    nationality: 'Spanish',
                    club: 'Liverpool',
                    season: 2009,
                    league: 'epl',
                    img: '',
                    appearances:22,
                    goals: 18,
                    // gpa:
                    },
                    {
                        firstname: 'Jermaine',
                        surname: 'Defoe',
                        dob: '07-10-1982',
                        nationality: 'English',
                        club: 'Tottenham Hotspur',
                        season: 2009,
                        league: 'epl',
                        img: 'https://th.bing.com/th/id/OIP.27BY-oRpDfsCFVmc3Qi4NgHaHU?w=185&h=183&c=7&r=0&o=5&pid=1.7',
                        appearances:34,
                        goals: 18,
                        // gpa:
                        },
                        {
                            firstname: 'Cesc',
                            surname: 'Fabregas',
                            dob: '04-05-1987',
                            nationality: 'Spanish',
                            club: 'Arsenal',
                            season: 2009,
                            league: 'epl',
                            img: '',
                            appearances:27,
                            goals: 15,
                            // gpa:
                            },
                            {
                                firstname: 'Emmanuel',
                                surname: 'Adebayor',
                                dob: '22-02-1984',
                                nationality: 'Togolgese',
                                club: 'Manchester City',
                                season: 2009,
                                league: 'epl',
                                img: '',
                                appearances:26,
                                goals: 14,
                                // gpa:
                                },
                                {
                                    firstname: 'Gabriel',
                                    surname: 'Agbonlahor',
                                    dob: '13-10-1986',
                                    nationality: 'English',
                                    club: 'Aston Villa',
                                    season: 2009,
                                    league: 'epl',
                                    img: '',
                                    appearances:36,
                                    goals: 13,
                                    // gpa:
                                    },
                                    {
                                        firstname: 'Louis',
                                        surname: 'Saha',
                                        dob: '08-08-1978',
                                        nationality: 'French',
                                        club: 'Everton',
                                        season: 2009,
                                        league: 'epl',
                                        img: 'https://th.bing.com/th/id/OIP.A2yUKa1dkP_3ccG5J70yJwHaIX?w=185&h=209&c=7&r=0&o=5&pid=1.7',
                                        appearances:33 ,
                                        goals: 13,
                                        // gpa:
                                        },

//2010
//epl
















]

export default players;