{
    firstname: 'Heung-min',
    surname: 'Son',
    dob: '08-07-1992',
    nationality: 'South Korean',
    club: 'Tottenham Hotspur',
    season: 2020,
    league: 'epl',
    img: 'https://th.bing.com/th?id=OIF.uzZey2eJVdgR%2fU3Y29hIsg&w=302&h=180&c=7&r=0&o=5&pid=1.7',
    appearances: 37,
    goals: 17,
    // gpa:
    },
{
    firstname: 'Heung-min',
    surname: 'Son',
    dob: '08-07-1992',
    nationality: 'South Korean',
    club: 'Tottenham Hotspur',
    season: 2021,
    league: 'epl',
    img: 'https://th.bing.com/th?id=OIF.uzZey2eJVdgR%2fU3Y29hIsg&w=302&h=180&c=7&r=0&o=5&pid=1.7',
    appearances: 35,
    goals: 23,
    // gpa:
    },
