{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2000,
    league: 'epl',
    img: '',
    appearances:35,
    goals: 17,
    // gpa:
    },
{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2000,
    league: 'epl',
    img: '',
    appearances:35,
    goals: 17,
    // gpa:
    },
{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2000,
    league: 'epl',
    img: '',
    appearances:35,
    goals: 17,
    // gpa:
    },
{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2000,
    league: 'epl',
    img: '',
    appearances:35,
    goals: 17,
    // gpa:
    },
{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2000,
    league: 'epl',
    img: '',
    appearances:35,
    goals: 17,
    // gpa:
    },
{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2000,
    league: 'epl',
    img: '',
    appearances:35,
    goals: 17,
    // gpa:
    },
{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2000,
    league: 'epl',
    img: '',
    appearances:35,
    goals: 17,
    // gpa:
    },
{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2001,
    league: 'epl',
    img: '',
    appearances:33,
    goals: 24,
    // gpa:
    },
{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2002,
    league: 'epl',
    img: '',
    appearances:37,
    goals: 24,
    // gpa:
    },
{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2003,
    league: 'epl',
    img: '',
    appearances:37,
    goals: 30,
    // gpa:
    },
{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2004,
    league: 'epl',
    img: '',
    appearances:32,
    goals: 25,
    // gpa:
    },
{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2005,
    league: 'epl',
    img: '',
    appearances:32,
    goals: 27,
    // gpa:
    },
{
    firstname: 'Thierry',
    surname: 'Henry',
    dob: '17-08-1977',
    nationality: 'French',
    club: 'Arsenal',
    season: 2006,
    league: 'epl',
    img: '',
    appearances:27,
    goals: 10,
    // gpa:
    },